const API = window.ROYAL_PET_ADMIN_API || localStorage.getItem('royalPetAdminApi') || '';
const DEMO_KEY='royalPetAppointments';
const DEMO_REVIEWS='royalPetReviews';
const demoAppointments=[
 {id:'demo-1',pet_name:'Боня',age:'3 роки',breed:'Шпіц, малий',owner_contact:'Олена, +380...',last_grooming:'2 місяці тому',preferred_time:'2026-09-12T11:00',additional_services:'Чистка зубів',home_care:'Хочу придбати домашній догляд',comment:'Спокійна собачка',status:'new'},
 {id:'demo-2',pet_name:'Мілка',age:'5 років',breed:'Мальтіпу',owner_contact:'Марія, +380...',last_grooming:'1 місяць тому',preferred_time:'2026-09-12T15:00',additional_services:'',home_care:'Поки не цікавить',comment:'',status:'confirmed'}
];
const days=[['monday','Понеділок'],['tuesday','Вівторок'],['wednesday','Середа'],['thursday','Четвер'],['friday','П’ятниця'],['saturday','Субота'],['sunday','Неділя']];
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function loadDemo(){try{return JSON.parse(localStorage.getItem(DEMO_KEY)||'null')||demoAppointments}catch{return demoAppointments}}
function saveDemo(v){localStorage.setItem(DEMO_KEY,JSON.stringify(v))}
function loadReviews(){try{return JSON.parse(localStorage.getItem(DEMO_REVIEWS)||'null')||[{id:'r1',name:'Анюта',rating:5,text:'Дуже задоволена результатом!',reply:'',status:'pending'}]}catch{return[]}}
async function api(path,opts={}){if(!API) throw new Error('API_NOT_CONFIGURED');const r=await fetch(API.replace(/\/$/,'')+path,{credentials:'include',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(!r.ok)throw new Error('API_ERROR');return r.json()}
async function getAppointments(){if(!API)return loadDemo();return api('/appointments')}
async function setStatus(id,status){if(!API){const a=loadDemo();const x=a.find(v=>v.id===id);if(x)x.status=status;saveDemo(a);return}return api(`/appointments/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status})})}
async function getHours(){if(!API){const saved=JSON.parse(localStorage.getItem('royalPetHours')||'null');return saved||{monday:'09:00–19:00',tuesday:'09:00–19:00',wednesday:'09:00–19:00',thursday:'09:00–19:00',friday:'09:00–19:00',saturday:'10:00–18:00',sunday:'Вихідний'}}return api('/hours')}
async function saveHours(data){if(!API){localStorage.setItem('royalPetHours',JSON.stringify(data));return}return api('/hours',{method:'PUT',body:JSON.stringify(data)})}
function setView(view){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));document.querySelector(`#view-${view}`).classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const titles={dashboard:'Огляд',appointments:'Записи',hours:'Графік роботи',reviews:'Відгуки',services:'Послуги'};document.getElementById('page-title').textContent=titles[view]||'Огляд';if(view==='dashboard')renderDashboard();if(view==='appointments')renderAppointments();if(view==='hours')renderHours();if(view==='reviews')renderReviews();if(view==='services')renderServices()}
async function renderDashboard(){const a=await getAppointments();const n=a.filter(x=>x.status==='new').length,c=a.filter(x=>x.status==='confirmed').length,d=a.filter(x=>x.status==='done').length;document.getElementById('new-count').textContent=n;document.getElementById('view-dashboard').innerHTML=`<div class="stats"><div class="stat"><small>Нові записи</small><strong>${n}</strong></div><div class="stat"><small>Підтверджені</small><strong>${c}</strong></div><div class="stat"><small>Виконані</small><strong>${d}</strong></div><div class="stat"><small>Всього</small><strong>${a.length}</strong></div></div><h3 class="section-title">Останні записи</h3><div class="card table-wrap"><table class="table"><thead><tr><th>Дата</th><th>Улюбленець</th><th>Власник</th><th>Статус</th></tr></thead><tbody>${a.slice().sort((x,y)=>String(y.preferred_time).localeCompare(String(x.preferred_time))).slice(0,6).map(x=>`<tr><td>${esc(formatDate(x.preferred_time))}</td><td>${esc(x.pet_name)}</td><td>${esc(x.owner_contact)}</td><td>${badge(x.status)}</td></tr>`).join('')}</tbody></table></div>`}
function formatDate(v){if(!v)return'—';const d=new Date(v);return isNaN(d)?v:d.toLocaleString('uk-UA',{dateStyle:'short',timeStyle:'short'})}
function badge(s){const labels={new:'Нова',confirmed:'Підтверджена',done:'Виконана',cancelled:'Скасована'};return `<span class="badge ${esc(s)}">${labels[s]||esc(s||'Нова')}</span>`}
async function renderAppointments(){const a=await getAppointments();document.getElementById('new-count').textContent=a.filter(x=>x.status==='new').length;document.getElementById('view-appointments').innerHTML=`<div class="toolbar"><input id="search" placeholder="Пошук по улюбленцю або власнику"><select id="status-filter"><option value="">Усі статуси</option><option value="new">Нові</option><option value="confirmed">Підтверджені</option><option value="done">Виконані</option><option value="cancelled">Скасовані</option></select></div><div class="card table-wrap"><table class="table"><thead><tr><th>Дата</th><th>Улюбленець</th><th>Порода</th><th>Контакт</th><th>Статус</th><th></th></tr></thead><tbody id="appointments-body"></tbody></table></div>`;const draw=()=>{const q=document.getElementById('search').value.toLowerCase(),s=document.getElementById('status-filter').value;document.getElementById('appointments-body').innerHTML=a.filter(x=>(!s||x.status===s)&&(!q||`${x.pet_name} ${x.owner_contact} ${x.breed}`.toLowerCase().includes(q))).map(x=>`<tr><td>${esc(formatDate(x.preferred_time))}</td><td><strong>${esc(x.pet_name)}</strong><br><small>${esc(x.age)}</small></td><td>${esc(x.breed)}</td><td>${esc(x.owner_contact)}</td><td>${badge(x.status)}</td><td><div class="actions">${x.status==='new'?`<button class="small-btn gold" data-action="confirm" data-id="${esc(x.id)}">Підтвердити</button>`:''}${x.status!=='done'?`<button class="small-btn" data-action="done" data-id="${esc(x.id)}">Виконано</button>`:''}<button class="small-btn danger" data-action="cancel" data-id="${esc(x.id)}">Скасувати</button><button class="small-btn" data-action="view" data-id="${esc(x.id)}">Деталі</button></div></td></tr>`).join('')};draw();document.getElementById('search').oninput=draw;document.getElementById('status-filter').onchange=draw;document.getElementById('appointments-body').onclick=async e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.id;if(b.dataset.action==='view'){const x=a.find(v=>v.id===id);showModal(`<h3>Запис ${esc(x.pet_name)}</h3><p><b>Вік:</b> ${esc(x.age)}</p><p><b>Порода:</b> ${esc(x.breed)}</p><p><b>Власник:</b> ${esc(x.owner_contact)}</p><p><b>Останній грумінг:</b> ${esc(x.last_grooming)}</p><p><b>Дата:</b> ${esc(formatDate(x.preferred_time))}</p><p><b>Додаткові послуги:</b> ${esc(x.additional_services||'—')}</p><p><b>Домашній догляд:</b> ${esc(x.home_care||'—')}</p><p><b>Коментар:</b> ${esc(x.comment||'—')}</p>`);return}const st={confirm:'confirmed',done:'done',cancel:'cancelled'}[b.dataset.action];if(st){await setStatus(id,st);renderAppointments();renderDashboard()}}}
async function renderHours(){const h=await getHours();document.getElementById('view-hours').innerHTML=`<div class="card"><p style="color:#aaa">Зміни збережуться в кабінеті та можуть бути підключені до сайту через API.</p><div class="days">${days.map(([k,l])=>`<div class="day"><strong>${l}</strong><input data-day="${k}" value="${esc(h[k]||'Вихідний')}"><button class="small-btn" data-day-save="${k}">Зберегти</button></div>`).join('')}</div></div>`;document.getElementById('view-hours').onclick=async e=>{const b=e.target.closest('[data-day-save]');if(!b)return;const data=await getHours();data[b.dataset.day]=document.querySelector(`[data-day="${b.dataset.day}"]`).value;await saveHours(data);b.textContent='Збережено ✓';setTimeout(()=>b.textContent='Зберегти',1200)}}
function renderReviews(){const r=loadReviews();document.getElementById('view-reviews').innerHTML=r.map(x=>`<div class="card review" style="margin-bottom:12px"><div><span class="badge">${esc(x.rating)} ★</span><h3>${esc(x.name)}</h3><p>${esc(x.text)}</p>${x.reply?`<p><b style="color:#d6ad55">Ваша відповідь:</b> ${esc(x.reply)}</p>`:''}</div><div>${x.status==='published'?'<span class="badge done">Опубліковано</span>':'<span class="badge new">На модерації</span>'}</div><div class="reply"><button class="small-btn gold" data-review="reply" data-id="${esc(x.id)}">Відповісти</button> <button class="small-btn" data-review="publish" data-id="${esc(x.id)}">Опублікувати</button> <button class="small-btn danger" data-review="hide" data-id="${esc(x.id)}">Приховати</button></div></div>`).join('')||'<div class="card">Нових відгуків немає.</div>';document.getElementById('view-reviews').onclick=e=>{const b=e.target.closest('[data-review]');if(!b)return;const x=r.find(v=>v.id===b.dataset.id);if(b.dataset.review==='reply'){showModal(`<h3>Відповідь на відгук</h3><p>${esc(x.text)}</p><textarea id="reply-text" rows="5" placeholder="Напишіть відповідь клієнту...">${esc(x.reply||'')}</textarea><div class="modal-actions"><button class="small-btn gold" id="save-reply">Зберегти відповідь</button></div>`);document.getElementById('save-reply').onclick=()=>{x.reply=document.getElementById('reply-text').value;localStorage.setItem(DEMO_REVIEWS,JSON.stringify(r));closeModal();renderReviews()}}else{x.status=b.dataset.review==='publish'?'published':'hidden';localStorage.setItem(DEMO_REVIEWS,JSON.stringify(r));renderReviews()}}}
function renderServices(){document.getElementById('view-services').innerHTML=`<div class="card"><h3>Послуги керуються через основну CMS</h3><p style="color:#aaa">Тут буде швидкий менеджер послуг після підключення API. Поки що використовуйте розділ «✂️ Послуги» в /admin/.</p><a class="site-link" href="../admin/">Відкрити CMS →</a></div>`}
function showModal(html){const d=document.createElement('div');d.className='modal-backdrop';d.id='modal';d.innerHTML=`<div class="modal">${html}<div class="modal-actions"><button class="small-btn" onclick="closeModal()">Закрити</button></div></div>`;document.body.appendChild(d)}function closeModal(){document.getElementById('modal')?.remove()}
async function login(user,pass){if(API){const r=await api('/auth/login',{method:'POST',body:JSON.stringify({username:user,password:pass})});if(r.ok){sessionStorage.setItem('royalPetAuth','1');return true}return false}return user==='admin'&&pass===localStorage.getItem('royalPetDemoPassword')}
function boot(){document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.getElementById('logout').onclick=()=>{sessionStorage.removeItem('royalPetAuth');location.reload()};document.getElementById('login-form').onsubmit=async e=>{e.preventDefault();const ok=await login(document.getElementById('login-user').value,document.getElementById('login-pass').value);if(ok){sessionStorage.setItem('royalPetAuth','1');document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');setView('dashboard')}else document.getElementById('login-error').textContent=API?'Невірний логін або пароль.':'Для демонстраційного режиму API ще не підключено.'};if(sessionStorage.getItem('royalPetAuth')==='1'){document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');setView('dashboard')}}
document.addEventListener('DOMContentLoaded',boot);
