(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const DAYS=[['monday','Пн'],['tuesday','Вт'],['wednesday','Ср'],['thursday','Чт'],['friday','Пт'],['saturday','Сб'],['sunday','Нд']];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const pad=n=>String(n).padStart(2,'0');
const dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parseDate=v=>{const d=new Date(String(v||'').replace(' ','T'));return isNaN(d)?null:d};
const parseIntervals=v=>[...String(v||'').matchAll(/(\d{1,2}):(\d{2})\s*[–—-]\s*(\d{1,2}):(\d{2})/g)].map(x=>({from:+x[1]*60 + +x[2],to:+x[3]*60 + +x[4]})).filter(x=>x.from<x.to);
async function get(path){const r=await fetch(API+path,{credentials:'include',cache:'no-store'});if(!r.ok)throw Error();return r.json()}
async function data(){const [a,h]=await Promise.all([get('/appointments'),get('/hours')]);return{appointments:Array.isArray(a)?a:[],hours:h&&typeof h==='object'?h:{}}}
function daySchedule(date,hours){const key=DAYS[(date.getDay()||7)-1][0];const raw=String(hours[`date:${dateKey(date)}`]??hours[key]??'').trim();if(!raw||/вихідний/i.test(raw)||/__DEFAULT__/i.test(raw))return[];return parseIntervals(raw)}
function slots(date,hours){return daySchedule(date,hours).reduce((n,r)=>n+Math.max(0,Math.ceil((r.to-r.from)/30)),0)}
function render(d){const root=document.getElementById('view-calendar');if(!root||root.classList.contains('hidden'))return;let panel=document.getElementById('rp-calendar-load');if(!panel){panel=document.createElement('div');panel.id='rp-calendar-load';panel.className='rp-calendar-load';root.appendChild(panel)}const now=new Date();const rows=[];for(let i=0;i<7;i++){const day=new Date(now);day.setHours(0,0,0,0);day.setDate(day.getDate()+i);const key=dateKey(day);const available=slots(day,d.hours);const items=d.appointments.filter(x=>{const dt=parseDate(x.preferred_time);return dt&&dateKey(dt)===key&&!['cancelled','deleted'].includes(String(x.status||'').toLowerCase())});const pct=available?Math.min(100,Math.round(items.length/available*100)):0;rows.push({day,available,booked:items.length,pct})}const avg=rows.filter(x=>x.available).reduce((s,x)=>s+x.pct,0)/(rows.filter(x=>x.available).length||1);panel.innerHTML=`<div class="rp-load-head"><div><h3>Завантаження майстра</h3><p>Навантаження на найближчі 7 днів за активними записами.</p></div><button type="button" class="rp-cal-btn" id="rp-load-refresh">Оновити</button></div><div class="rp-load-summary"><div><small>Середнє завантаження</small><strong>${Math.round(avg)}%</strong></div><div><small>Записів на 7 днів</small><strong>${rows.reduce((s,x)=>s+x.booked,0)}</strong></div><div><small>Вільних слотів</small><strong>${rows.reduce((s,x)=>s+x.available,0)-rows.reduce((s,x)=>s+x.booked,0)}</strong></div></div><div class="rp-load-grid">${rows.map(x=>{const label=x.day.toLocaleDateString('uk-UA',{weekday:'short'}).replace('.','');const risk=x.available===0?'off':x.pct>=80?'high':x.pct>=50?'mid':'low';return `<div class="rp-load-row"><div><b>${esc(label)}</b><span>${x.day.getDate()}.${pad(x.day.getMonth()+1)}</span></div><div class="rp-load-bar"><i class="${risk}" style="width:${x.pct}%"></i></div><div class="rp-load-value">${x.booked}/${x.available} <small>${x.available?x.pct+'%':'Вихідний'}</small></div></div>`}).join('')}</div>`;panel.querySelector('#rp-load-refresh').onclick=()=>load()}
function style(){if(document.getElementById('rp-calendar-load-style'))return;const s=document.createElement('style');s.id='rp-calendar-load-style';s.textContent='.rp-calendar-load{margin-top:16px;padding:16px;border:1px solid rgba(215,173,85,.18);border-radius:14px;background:rgba(255,255,255,.02)}.rp-load-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.rp-load-head h3{margin:0 0 4px}.rp-load-head p{margin:0;color:#969087;font-size:12px}.rp-load-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:14px 0}.rp-load-summary>div{padding:12px;border-radius:12px;border:1px solid rgba(255,255,255,.07);background:rgba(255,255,255,.025)}.rp-load-summary small{display:block;color:#969087;margin-bottom:4px}.rp-load-summary strong{font-size:20px;color:#d7ad55}.rp-load-grid{display:grid;gap:8px}.rp-load-row{display:grid;grid-template-columns:85px 1fr 90px;gap:10px;align-items:center}.rp-load-row>div:first-child{display:flex;justify-content:space-between;gap:8px}.rp-load-row span{color:#8f8a80;font-size:11px}.rp-load-bar{height:10px;border-radius:99px;background:rgba(255,255,255,.07);overflow:hidden}.rp-load-bar i{display:block;height:100%;border-radius:99px}.rp-load-bar i.low{background:#58b96b}.rp-load-bar i.mid{background:#d7ad55}.rp-load-bar i.high{background:#d95b68}.rp-load-value{text-align:right;font-weight:700}.rp-load-value small{display:block;color:#969087;font-weight:400;font-size:10px}@media(max-width:600px){.rp-load-summary{grid-template-columns:1fr}.rp-load-row{grid-template-columns:70px 1fr 70px;font-size:12px}.rp-load-row>div:first-child{display:grid;gap:1px}.rp-load-head{align-items:center}}';document.head.appendChild(s)}
let timer=0;async function load(){try{const d=await data();render(d)}catch{const panel=document.getElementById('rp-calendar-load');if(panel)panel.innerHTML='<div class="rp-cal-error">Не вдалося завантажити завантаження.</div>'}}
function boot(){style();const root=document.getElementById('view-calendar');if(!root)return;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{if(!document.getElementById('rp-calendar-load')||!document.getElementById('rp-calendar-load')?.dataset.ready)load()},120)}).observe(root,{childList:true,subtree:true});load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();