(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=v=>Number(v||0).toLocaleString('uk-UA');
const coatLabel=v=>({none:'Нормальний стан',light:'Є ковтуни',severe:'Сильні ковтуни / запущена шерсть'})[v]||'Нормальний стан';
const statusLabel=v=>({new:'Нова',confirmed:'Підтверджена',done:'Виконана',cancelled:'Скасована',deleted:'Видалена'})[v]||v||'—';
async function getAppointments(){const r=await fetch(API+'/appointments',{credentials:'include',cache:'no-store'});if(!r.ok)throw Error('Не вдалося отримати записи');const data=await r.json();return Array.isArray(data)?data:(Array.isArray(data?.results)?data.results:[])}
async function setStatus(id,status){const r=await fetch(API+'/appointments/'+encodeURIComponent(id),{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||`API ${r.status}`);return j}
function parseMeta(x){try{const o=JSON.parse(x?.additional_services||'');if(o&&typeof o==='object'&&!Array.isArray(o))return o}catch{}return{}}
function serviceNames(m){return Array.isArray(m.services)?m.services.map(v=>typeof v==='string'?v:v?.title).filter(Boolean):[]}
function setActive(){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='calendar'));const t=document.getElementById('page-title');if(t)t.textContent='Календар'}
function dateOf(v){const d=new Date(String(v||'').replace(' ','T'));return isNaN(d)?null:d}
function dayKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dayLabel(d){return d.toLocaleDateString('uk-UA',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
function addStyles(){if(document.getElementById('rp-cal-actions-style'))return;const s=document.createElement('style');s.id='rp-cal-actions-style';s.textContent=`.rp-cal-actions{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}.rp-cal-actions .small-btn{margin:0}.rp-client-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.68);z-index:9999;display:grid;place-items:center;padding:18px}.rp-client-modal{width:min(620px,100%);max-height:90vh;overflow:auto;background:#111;border:1px solid rgba(215,173,85,.28);border-radius:18px;box-shadow:0 24px 70px rgba(0,0,0,.45);padding:20px;color:#eee}.rp-client-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.rp-client-head h3{margin:0 0 3px}.rp-client-sub{color:#aaa;font-size:12px}.rp-client-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:16px}.rp-client-field{padding:11px;border:1px solid rgba(255,255,255,.07);border-radius:12px;background:rgba(255,255,255,.025)}.rp-client-field small{display:block;color:#8f8a80;margin-bottom:3px}.rp-client-field b{display:block;word-break:break-word}.rp-client-field.full{grid-column:1/-1}.rp-client-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}@media(max-width:600px){.rp-client-grid{grid-template-columns:1fr}.rp-client-field.full{grid-column:auto}.rp-cal-actions{gap:5px}.rp-cal-actions .small-btn{font-size:11px;padding:7px 8px}}`;document.head.appendChild(s)}
function clientCard(x){addStyles();document.getElementById('rp-client-backdrop')?.remove();const m=parseMeta(x);const d=dateOf(x.preferred_time);const services=serviceNames(m);const back=document.createElement('div');back.id='rp-client-backdrop';back.className='rp-client-backdrop';back.innerHTML=`<div class="rp-client-modal" role="dialog" aria-modal="true"><div class="rp-client-head"><div><div class="gold-label">ROYAL PET</div><h3>${esc(x.owner_name||'Клієнт')}</h3><div class="rp-client-sub">Картка за записом · ${esc(x.pet_name||'Улюбленець')}</div></div><button type="button" class="small-btn" data-close-client>✕</button></div><div class="rp-client-grid"><div class="rp-client-field"><small>Телефон</small><b>${esc(x.owner_contact||'—')}</b></div><div class="rp-client-field"><small>Запис</small><b>${d?esc(d.toLocaleString('uk-UA',{dateStyle:'short',timeStyle:'short'})):'—'}</b></div><div class="rp-client-field"><small>Улюбленець</small><b>${esc(x.pet_name||'—')}</b></div><div class="rp-client-field"><small>Порода / тип</small><b>${esc(x.breed||'Без породи')} · ${esc(m.animal_type==='cat'?'Кіт':'Собака')}</b></div><div class="rp-client-field"><small>Вік</small><b>${esc(x.age||'—')}</b></div><div class="rp-client-field"><small>Останній грумінг</small><b>${esc(x.last_grooming||'—')}</b></div><div class="rp-client-field full"><small>Послуги</small><b>${esc(services.length?services.join(', '):'Послуги не вказані')}</b></div><div class="rp-client-field full"><small>Домашній догляд</small><b>${esc(x.home_care||'—')}</b></div><div class="rp-client-field full"><small>Коментар</small><b>${esc(x.comment||'—')}</b></div></div><div class="rp-client-actions"><button type="button" class="small-btn gold" data-close-client>Закрити</button></div></div>`;document.body.appendChild(back);const close=()=>back.remove();back.querySelectorAll('[data-close-client]').forEach(b=>b.addEventListener('click',close));back.addEventListener('click',e=>{if(e.target===back)close()});document.addEventListener('keydown',function escKey(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',escKey)}})}
function actionButtons(x){const s=String(x.status||'new').toLowerCase();const parts=[];if(s==='new')parts.push(`<button class="small-btn gold" type="button" data-cal-status="confirmed" data-id="${esc(x.id)}">Підтвердити</button>`);if(!['done','cancelled'].includes(s))parts.push(`<button class="small-btn" type="button" data-cal-status="done" data-id="${esc(x.id)}">Виконано</button>`);if(!['done','cancelled'].includes(s))parts.push(`<button class="small-btn danger" type="button" data-cal-status="cancelled" data-id="${esc(x.id)}">Скасувати</button>`);if(!['done','cancelled'].includes(s))parts.push(`<button class="small-btn" type="button" data-cal-reschedule="${esc(x.id)}">Перенести</button>`);parts.push(`<button class="small-btn" type="button" data-cal-client="${esc(x.id)}">Клієнт</button>`);parts.push(`<button class="small-btn gold" type="button" data-cal-edit="${esc(x.id)}">Відкрити</button>`);return `<div class="rp-cal-actions">${parts.join('')}</div>`}
function card(x){const m=parseMeta(x),svc=serviceNames(m),price=m.final_price??m.estimated_total??'',d=dateOf(x.preferred_time);if(!d)return '';const tm=d.toLocaleTimeString('uk-UA',{hour:'2-digit',minute:'2-digit'});return `<div class="card calendar-item"><div class="calendar-time">${esc(tm)}</div><div><b>${esc(x.pet_name||'—')}</b><span>${esc(x.breed||'Без породи')}</span><span>${m.animal_type==='cat'?'Кіт':'Собака'}${m.breed_category?` · ${esc(m.breed_category)}`:''}</span></div><div><b>${esc(x.owner_name||'—')}</b><span>${esc(x.owner_contact||'')}</span></div><div><span>${svc.length?esc(svc.join(', ')):'Послуги не вказані'}</span><span>Стан шерсті: ${esc(coatLabel(m.coat_condition))}</span>${price!==''?`<span>${esc(m.final_price!=null?'До оплати: '+money(price)+' грн':'Орієнтовно: '+money(price)+' грн')}</span>`:''}</div><div><span class="badge ${esc(x.status||'new')}">${esc(statusLabel(x.status))}</span>${actionButtons(x)}</div></div>`}
async function renderCalendar(){const root=document.getElementById('view-calendar');if(!root)return;document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));root.classList.remove('hidden');setActive();root.innerHTML='<div class="card">Завантаження календаря…</div>';try{const all=await getAppointments();const records=all.filter(x=>!['cancelled','deleted'].includes(String(x.status||'').toLowerCase())&&dateOf(x.preferred_time));records.sort((a,b)=>dateOf(a.preferred_time)-dateOf(b.preferred_time));const groups=new Map();records.forEach(x=>{const d=dateOf(x.preferred_time),key=dayKey(d);if(!groups.has(key))groups.set(key,{date:d,items:[]});groups.get(key).items.push(x)});const html=[...groups.values()].map(g=>`<section class="calendar-day"><h3>${esc(dayLabel(g.date))}</h3><div class="calendar-list">${g.items.map(card).join('')}</div></section>`).join('');root.innerHTML=`<div class="toolbar"><div><h3>Записи в календарі</h3><span style="color:#aaa">Всього записів: ${records.length}</span></div><button class="small-btn" type="button" id="calendar-refresh">Оновити</button></div>${html||'<div class="card">Записів у календарі поки немає.</div>'}`;root.querySelector('#calendar-refresh')?.addEventListener('click',renderCalendar);root.querySelectorAll('[data-cal-edit]').forEach(btn=>btn.addEventListener('click',()=>{const x=records.find(v=>v.id===btn.dataset.calEdit);if(x){if(typeof window.showAppointment==='function')window.showAppointment(x);else if(typeof window.royalPetOpenAppointment==='function')window.royalPetOpenAppointment(x)}}));root.querySelectorAll('[data-cal-reschedule]').forEach(btn=>btn.addEventListener('click',()=>{const x=records.find(v=>v.id===btn.dataset.calReschedule);if(x){if(typeof window.showAppointment==='function')window.showAppointment(x);else if(typeof window.royalPetOpenAppointment==='function')window.royalPetOpenAppointment(x)}}));root.querySelectorAll('[data-cal-client]').forEach(btn=>btn.addEventListener('click',()=>{const x=records.find(v=>v.id===btn.dataset.calClient);if(x)clientCard(x)}));root.querySelectorAll('[data-cal-status]').forEach(btn=>btn.addEventListener('click',async()=>{const id=btn.dataset.id,status=btn.dataset.calStatus,x=records.find(v=>v.id===id);if(!x)return;const text=status==='confirmed'?'Підтвердити цей запис?':status==='done'?`Позначити запис для ${x.pet_name||'улюбленця'} як виконаний?`:`Скасувати запис для ${x.pet_name||'улюбленця'}?`;if(!confirm(text))return;btn.disabled=true;try{await setStatus(id,status);await renderCalendar()}catch(e){btn.disabled=false;alert(e.message)}}))}catch(e){root.innerHTML=`<div class="card error">Помилка завантаження календаря: ${esc(e.message)}</div>`}}
function hook(){document.addEventListener('click',e=>{const btn=e.target.closest('.sidebar .nav-item[data-view="calendar"], [data-mobile-view="calendar"]');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();renderCalendar()},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook,{once:true});else hook();window.royalPetCalendar=renderCalendar;
})();