(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const fmt=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('uk-UA',{dateStyle:'short',timeStyle:'short'})};
const phoneKey=v=>{const digits=String(v||'').replace(/\D/g,'');return digits||String(v||'').trim().toLowerCase()};
const money=v=>Number(v||0).toLocaleString('uk-UA');
const statusLabel=v=>({new:'Нова',confirmed:'Підтверджена',done:'Виконана',cancelled:'Скасована',deleted:'Видалена'})[v]||v||'—';
async function load(){const r=await fetch(API+'/appointments',{credentials:'include',cache:'no-store'});if(!r.ok)throw Error('Не вдалося завантажити клієнтів');return r.json()}
function meta(x){if(x?.additional_services){try{const m=JSON.parse(x.additional_services);if(m&&typeof m==='object'&&!Array.isArray(m))return m}catch{}}return{services:[]}}
function priceOf(x){const m=meta(x);const final=m.final_price??x.final_price;const estimated=m.estimated_total??x.estimated_total;if(final!==null&&final!==undefined&&String(final)!==''&&!Number.isNaN(Number(final)))return Number(final);if(estimated!==null&&estimated!==undefined&&String(estimated)!==''&&!Number.isNaN(Number(estimated)))return Number(estimated);if(Array.isArray(m.services))return m.services.reduce((s,v)=>s+(Number(v?.price)||0)+(Number(v?.surcharge||v?.coat_surcharge)||0),0);return 0}
function validVisits(c){return c.visits.filter(x=>!['deleted'].includes(String(x.status||'').toLowerCase()))}
function stats(c){const visits=validVisits(c).slice().sort((a,b)=>new Date(a.preferred_time)-new Date(b.preferred_time));const now=Date.now();const future=visits.filter(x=>{const d=new Date(x.preferred_time);return !isNaN(d)&&d.getTime()>=now&&!['cancelled','deleted'].includes(String(x.status||'').toLowerCase())}).sort((a,b)=>new Date(a.preferred_time)-new Date(b.preferred_time));const past=visits.filter(x=>{const d=new Date(x.preferred_time);return !isNaN(d)&&d.getTime()<now&&!['cancelled','deleted'].includes(String(x.status||'').toLowerCase())});const spent=past.reduce((s,x)=>s+priceOf(x),0);return{visits:visits.length,pastCount:past.length,next:future[0]||null,last:past[past.length-1]||null,spent}}
function show(){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));let root=document.getElementById('view-clients');if(!root){root=document.createElement('section');root.id='view-clients';root.className='view';document.querySelector('.main')?.appendChild(root)}root.classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='clients'));const title=document.getElementById('page-title');if(title)title.textContent='Клієнти';root.innerHTML='<div class="toolbar"><div><h3>Клієнти</h3><span style="color:#aaa">Історія, улюбленці та наступні записи в одній картці.</span></div><button class="small-btn" id="clients-refresh">Оновити</button></div><div class="card"><input id="clients-search" style="width:100%;box-sizing:border-box" placeholder="Пошук за ім’ям, телефоном або улюбленцем"></div><div id="clients-list" class="clients-list">Завантаження…</div>';load().then(a=>render(root,a)).catch(e=>{const list=root.querySelector('#clients-list');if(list)list.innerHTML=`<div class="card error">${esc(e.message)}</div>`});const refresh=root.querySelector('#clients-refresh');if(refresh)refresh.onclick=show}
function render(root,a){const map=new Map();(Array.isArray(a)?a:[]).filter(x=>x.status!=='deleted').forEach(x=>{const key=phoneKey(x.owner_contact);if(!key)return;let c=map.get(key);if(!c){c={name:x.owner_name||'—',phone:x.owner_contact||'—',pets:new Set(),visits:[]};map.set(key,c)}if(c.name==='—'&&x.owner_name)c.name=x.owner_name;if(x.owner_contact)c.phone=x.owner_contact;if(x.pet_name)c.pets.add(x.pet_name);c.visits.push(x)});const clients=[...map.values()].map(c=>{c.stats=stats(c);return c}).sort((a,b)=>new Date(b.stats.last?.preferred_time||b.visits[0]?.preferred_time||0)-new Date(a.stats.last?.preferred_time||a.visits[0]?.preferred_time||0));const list=root.querySelector('#clients-list');list.innerHTML=clients.length?clients.map((c,i)=>{const s=c.stats;return `<button class="card client-card" type="button" data-client="${i}"><div><b>${esc(c.name)}</b><span>${esc(c.phone)}</span></div><div><span>${esc([...c.pets].join(', ')||'Без улюбленця')}</span><small>${s.pastCount} візитів · останній: ${esc(fmt(s.last?.preferred_time))}</small></div><div><small>Наступний: ${esc(s.next?fmt(s.next.preferred_time):'Немає')}</small><small>Витрачено: ${money(s.spent)} грн</small></div><strong>›</strong></button>`}).join(''):'<div class="card">Клієнтів поки немає.</div>';const search=root.querySelector('#clients-search');if(search)search.oninput=()=>{const q=search.value.toLowerCase().trim();root.querySelectorAll('[data-client]').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(q))};list.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>card(clients[Number(b.dataset.client)]))}
function card(c){const visits=c.visits.slice().sort((a,b)=>new Date(b.preferred_time)-new Date(a.preferred_time));const s=c.stats||stats(c);const petRows=[...c.pets].map(p=>`<span class="rp-client-pet">${esc(p)}</span>`).join('');const rows=visits.map(x=>{const m=meta(x),services=Array.isArray(m.services)?m.services.map(v=>typeof v==='string'?v:v.title).filter(Boolean).join(', '):String(m.services||'');return `<tr><td>${esc(fmt(x.preferred_time))}</td><td>${esc(x.pet_name||'—')}</td><td>${esc(x.breed||'—')}</td><td>${esc(services||'—')}</td><td>${esc(statusLabel(x.status))}</td><td>${money(priceOf(x))} грн</td><td>${esc(x.comment||'—')}</td></tr>`}).join('');const next=s.next?`<p><b>Наступний грумінг:</b> ${esc(fmt(s.next.preferred_time))} · ${esc(s.next.pet_name||'—')}</p>`:'<p><b>Наступний грумінг:</b> немає запланованого</p>';const last=s.last?`<p><b>Останній візит:</b> ${esc(fmt(s.last.preferred_time))} · ${esc(s.last.pet_name||'—')}</p>`:'<p><b>Останній візит:</b> немає</p>';const html=`<div class="rp-crm-head"><div><div class="gold-label">ROYAL PET</div><h3>${esc(c.name)}</h3><p class="rp-muted">${esc(c.phone)}</p></div><div class="rp-crm-pets">${petRows||'<span class="rp-client-pet">Без улюбленця</span>'}</div></div><div class="rp-crm-stats"><div><small>Візити</small><strong>${s.pastCount}</strong></div><div><small>Улюбленці</small><strong>${c.pets.size}</strong></div><div><small>Витрачено</small><strong>${money(s.spent)} грн</strong></div><div><small>Записів усього</small><strong>${s.visits}</strong></div></div><div class="card rp-crm-next">${last}${next}</div><h4>Історія записів</h4><div class="table-wrap"><table class="table"><thead><tr><th>Дата</th><th>Улюбленець</th><th>Порода</th><th>Послуги</th><th>Статус</th><th>Сума</th><th>Коментар</th></tr></thead><tbody>${rows||'<tr><td colspan="7">Історії немає.</td></tr>'}</tbody></table></div><div class="modal-actions"><button class="small-btn" onclick="closeModal()">Закрити</button></div>`;window.modal?.(html)}
function styles(){if(document.getElementById('clients-style'))return;const s=document.createElement('style');s.id='clients-style';s.textContent='.clients-list{display:grid;gap:10px;margin-top:14px}.client-card{width:100%;display:grid;grid-template-columns:1.15fr 1fr 1fr auto;gap:16px;text-align:left;align-items:center;cursor:pointer;border:1px solid rgba(255,255,255,.08)}.client-card>div{display:grid;gap:4px}.client-card span,.client-card small{color:#aaa}.client-card strong{font-size:1.5rem}.rp-crm-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.rp-crm-head h3{margin:2px 0}.rp-crm-pets{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.rp-client-pet{padding:6px 9px;border-radius:999px;background:rgba(215,173,85,.1);border:1px solid rgba(215,173,85,.25);color:#d7ad55!important;font-size:12px}.rp-crm-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:14px 0}.rp-crm-stats>div{padding:12px;border:1px solid rgba(255,255,255,.07);border-radius:12px;background:rgba(255,255,255,.025)}.rp-crm-stats small{display:block;color:#8f8a80;margin-bottom:4px}.rp-crm-stats strong{font-size:17px;color:#d7ad55}.rp-crm-next{margin-bottom:14px}.rp-muted{color:#999}.rp-crm-next p{margin:5px 0}@media(max-width:900px){.client-card{grid-template-columns:1fr 1fr}.rp-crm-stats{grid-template-columns:1fr 1fr}}@media(max-width:600px){.client-card{grid-template-columns:1fr}.rp-crm-head{display:grid}.rp-crm-pets{justify-content:flex-start}.rp-crm-stats{grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
function boot(){styles();const b=document.querySelector('.sidebar .nav-item[data-view="clients"]');if(b)b.onclick=show;window.royalPetShowClients=show}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
