(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('uk-UA',{dateStyle:'short',timeStyle:'short'})};
const phoneKey=v=>{const digits=String(v||'').replace(/\D/g,'');return digits||String(v||'').trim().toLowerCase()};
async function load(){const r=await fetch(API+'/appointments',{credentials:'include',cache:'no-store'});if(!r.ok)throw Error('Не вдалося завантажити клієнтів');return r.json()}
function meta(x){if(x?.additional_services){try{const m=JSON.parse(x.additional_services);if(m&&typeof m==='object'&&!Array.isArray(m))return m}catch{}}return{services:[]}}
function show(){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));let root=document.getElementById('view-clients');if(!root){root=document.createElement('section');root.id='view-clients';root.className='view';document.querySelector('.main')?.appendChild(root)}root.classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='clients'));const title=document.getElementById('page-title');if(title)title.textContent='Клієнти';root.innerHTML='<div class="toolbar"><div><h3>Клієнти</h3><span style="color:#aaa">Один клієнт = один номер телефону. Усі записи та улюбленці зібрані в одній картці.</span></div><button class="small-btn" id="clients-refresh">Оновити</button></div><div class="card"><input id="clients-search" style="width:100%;box-sizing:border-box" placeholder="Пошук за ім’ям, телефоном або улюбленцем"></div><div id="clients-list" class="clients-list">Завантаження…</div>';load().then(a=>render(root,a)).catch(e=>{const list=root.querySelector('#clients-list');if(list)list.innerHTML=`<div class="card error">${esc(e.message)}</div>`});const refresh=root.querySelector('#clients-refresh');if(refresh)refresh.onclick=show}
function render(root,a){const map=new Map();(Array.isArray(a)?a:[]).filter(x=>x.status!=='deleted').forEach(x=>{const key=phoneKey(x.owner_contact);if(!key)return;let c=map.get(key);if(!c){c={name:x.owner_name||'—',phone:x.owner_contact||'—',pets:new Set(),visits:[]};map.set(key,c)}if(c.name==='—'&&x.owner_name)c.name=x.owner_name;if(x.owner_contact)c.phone=x.owner_contact;if(x.pet_name)c.pets.add(x.pet_name);c.visits.push(x)});const clients=[...map.values()].sort((a,b)=>new Date(b.visits.map(x=>x.preferred_time).sort().pop()||0)-new Date(a.visits.map(x=>x.preferred_time).sort().pop()||0));const list=root.querySelector('#clients-list');list.innerHTML=clients.length?clients.map((c,i)=>{const last=c.visits.slice().sort((x,y)=>new Date(y.preferred_time)-new Date(x.preferred_time))[0];return `<button class="card client-card" type="button" data-client="${i}"><div><b>${esc(c.name)}</b><span>${esc(c.phone)}</span></div><div><span>${esc([...c.pets].join(', ')||'Без улюбленця')}</span><small>${c.visits.length} записів · останній: ${esc(fmt(last?.preferred_time))}</small></div><strong>›</strong></button>`}).join(''):'<div class="card">Клієнтів поки немає.</div>';const search=root.querySelector('#clients-search');if(search)search.oninput=()=>{const q=search.value.toLowerCase().trim();root.querySelectorAll('[data-client]').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(q))};list.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>card(clients[Number(b.dataset.client)]))}
function card(c){const visits=c.visits.slice().sort((a,b)=>new Date(b.preferred_time)-new Date(a.preferred_time));const rows=visits.map(x=>{const m=meta(x),services=Array.isArray(m.services)?m.services.map(v=>typeof v==='string'?v:v.title).filter(Boolean).join(', '):String(m.services||'');return `<tr><td>${esc(fmt(x.preferred_time))}</td><td>${esc(x.pet_name||'—')}</td><td>${esc(x.breed||'—')}</td><td>${esc(services||'—')}</td><td>${esc(x.last_grooming||'—')}</td><td>${esc(x.home_care||'—')}</td><td>${esc(x.comment||'—')}</td><td>${esc(({new:'Нова',confirmed:'Підтверджена',done:'Виконана',cancelled:'Скасована'})[x.status]||x.status||'—')}</td></tr>`}).join('');const html=`<h3>${esc(c.name)}</h3><div class="card" style="margin-bottom:14px"><p><b>Телефон:</b> ${esc(c.phone)}</p><p><b>Улюбленці:</b> ${esc([...c.pets].join(', ')||'—')}</p><p><b>Всього візитів:</b> ${c.visits.length}</p></div><div class="table-wrap"><table class="table"><thead><tr><th>Дата</th><th>Улюбленець</th><th>Порода</th><th>Послуги</th><th>Останній грумінг</th><th>Домашній догляд</th><th>Коментар</th><th>Статус</th></tr></thead><tbody>${rows}</tbody></table></div><div class="modal-actions"><button class="small-btn" onclick="closeModal()">Закрити</button></div>`;window.modal?.(html)}
function styles(){if(document.getElementById('clients-style'))return;const s=document.createElement('style');s.id='clients-style';s.textContent='.clients-list{display:grid;gap:10px;margin-top:14px}.client-card{width:100%;display:grid;grid-template-columns:1.2fr 1fr auto;gap:16px;text-align:left;align-items:center;cursor:pointer;border:1px solid rgba(255,255,255,.08)}.client-card>div{display:grid;gap:4px}.client-card span,.client-card small{color:#aaa}.client-card strong{font-size:1.5rem}@media(max-width:700px){.client-card{grid-template-columns:1fr;gap:8px}.client-card strong{display:none}}';document.head.appendChild(s)}
function boot(){styles();const b=document.querySelector('.sidebar .nav-item[data-view="clients"]');if(b)b.onclick=show;window.royalPetShowClients=show}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
