(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const money=v=>Number(v||0).toLocaleString('uk-UA');
const statusLabel=v=>({new:'Нова',confirmed:'Підтверджена',done:'Виконана',cancelled:'Скасована',deleted:'Видалена'})[v]||v||'—';
const meta=x=>{if(x?.additional_services){try{const m=JSON.parse(x.additional_services);if(m&&typeof m==='object'&&!Array.isArray(m))return m}catch{}}return{services:[]}};
const priceOf=x=>{const m=meta(x),v=m.final_price??x.final_price??m.estimated_total??x.estimated_total;if(v!==null&&v!==undefined&&String(v)!==''&&!Number.isNaN(Number(v)))return Number(v);if(Array.isArray(m.services))return m.services.reduce((s,z)=>s+(Number(z?.price)||0)+(Number(z?.surcharge||z?.coat_surcharge)||0),0);return 0};
const active=x=>!['cancelled','deleted'].includes(String(x?.status||'').toLowerCase());
function serviceNames(x){const m=meta(x);if(!Array.isArray(m.services))return String(m.services||'').split(',').map(s=>s.trim()).filter(Boolean);return m.services.map(v=>typeof v==='string'?v:(v?.title||v?.name||'')).filter(Boolean)}
async function load(){const r=await fetch(API+'/appointments',{credentials:'include',cache:'no-store'});if(!r.ok)throw Error('Не вдалося завантажити статистику');return r.json()}
function periodStats(a){const now=new Date(),todayKey=now.toLocaleDateString('en-CA');const monthStart=new Date(now.getFullYear(),now.getMonth(),1);const completed=a.filter(x=>x.status==='done');const monthDone=completed.filter(x=>{const d=new Date(x.preferred_time);return !isNaN(d)&&d>=monthStart&&d<=now});const today=a.filter(x=>{const d=new Date(x.preferred_time);return !isNaN(d)&&d.toLocaleDateString('en-CA')===todayKey&&active(x)});const upcoming=a.filter(x=>active(x)&&['new','confirmed'].includes(x.status)&&new Date(x.preferred_time)>=now).sort((p,q)=>new Date(p.preferred_time)-new Date(q.preferred_time));const clients=new Map();a.filter(x=>active(x)).forEach(x=>{const k=String(x.owner_contact||x.owner_name||'').trim().toLowerCase();if(k)clients.set(k,(clients.get(k)||0)+1)});const returning=[...clients.values()].filter(v=>v>1).length;const services=new Map();monthDone.forEach(x=>serviceNames(x).forEach(n=>services.set(n,(services.get(n)||0)+1)));const top=[...services.entries()].sort((p,q)=>q[1]-p[1]).slice(0,5);return{monthRevenue:monthDone.reduce((s,x)=>s+priceOf(x),0),monthVisits:monthDone.length,today:today.length,upcoming:upcoming.length,clients:clients.size,returning,top,cancelled:a.filter(x=>x.status==='cancelled').length,allDone:completed.length}}
function render(){const root=document.getElementById('view-dashboard');if(!root||root.classList.contains('hidden'))return;load().then(a=>{if(root.querySelector('#rp-dashboard-stats'))return;const s=periodStats(Array.isArray(a)?a:[]);const top=s.top.length?s.top.map(([n,c])=>`<div class="rp-stat-row"><span>${esc(n)}</span><b>${c}</b></div>`).join(''):'<div class="rp-muted">Ще немає виконаних послуг цього місяця.</div>';const block=document.createElement('div');block.id='rp-dashboard-stats';block.innerHTML=`<h3 class="section-title">Статистика студії</h3><div class="rp-kpi-grid"><div class="rp-kpi"><small>Виручка цього місяця</small><strong>${money(s.monthRevenue)} грн</strong><span>за виконаними записами</span></div><div class="rp-kpi"><small>Виконані цього місяця</small><strong>${s.monthVisits}</strong><span>завершених візитів</span></div><div class="rp-kpi"><small>Записи сьогодні</small><strong>${s.today}</strong><span>активні заявки</span></div><div class="rp-kpi"><small>Найближчі записи</small><strong>${s.upcoming}</strong><span>підтверджені та нові</span></div></div><div class="rp-business-grid"><div class="card"><h4>Клієнти</h4><div class="rp-big-number">${s.clients}</div><p class="rp-muted">активних клієнтів</p><p><b>${s.returning}</b> повертаються повторно</p></div><div class="card"><h4>Найпопулярніші послуги</h4>${top}</div><div class="card"><h4>Контроль записів</h4><div class="rp-control"><span>Виконано всього</span><b>${s.allDone}</b></div><div class="rp-control"><span>Скасовано</span><b>${s.cancelled}</b></div></div></div>`;root.appendChild(block)}).catch(()=>{}).finally(()=>applyStyles())}
function applyStyles(){if(document.getElementById('rp-dashboard-stats-style'))return;const s=document.createElement('style');s.id='rp-dashboard-stats-style';s.textContent='.rp-kpi-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0 16px}.rp-kpi{padding:15px;border:1px solid rgba(255,255,255,.07);border-radius:14px;background:rgba(255,255,255,.025);display:grid;gap:5px}.rp-kpi small,.rp-kpi span,.rp-muted{color:#969087}.rp-kpi strong,.rp-big-number{font-size:23px;color:#d7ad55}.rp-business-grid{display:grid;grid-template-columns:1fr 1.3fr 1fr;gap:10px}.rp-business-grid .card{min-height:140px}.rp-business-grid h4{margin:0 0 12px}.rp-stat-row,.rp-control{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px solid rgba(255,255,255,.06)}.rp-stat-row:last-child,.rp-control:last-child{border-bottom:0}.rp-big-number{font-size:30px;font-weight:700;margin-top:3px}@media(max-width:950px){.rp-kpi-grid{grid-template-columns:1fr 1fr}.rp-business-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.rp-kpi-grid,.rp-business-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function boot(){applyStyles();const root=document.getElementById('view-dashboard');if(!root)return;new MutationObserver(()=>render()).observe(root,{childList:true});render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
