(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d)?v:d.toLocaleString('uk-UA',{dateStyle:'short',timeStyle:'short'})};
async function getAppointments(){const r=await fetch(API+'/appointments',{credentials:'include'});if(!r.ok)throw Error('Не вдалося отримати записи');return r.json()}
function addNav(){const nav=document.querySelector('.sidebar nav');if(!nav||document.querySelector('[data-view="calendar"]'))return;nav.insertAdjacentHTML('beforeend','<button class="nav-item" data-view="calendar">▦ <span>Календар</span></button><button class="nav-item" data-view="clients">♙ <span>Клієнти</span></button>');['calendar','clients'].forEach(v=>document.querySelector(`[data-view="${v}"]`).onclick=()=>showEnhanced(v))}
function addViews(){const main=document.querySelector('.main');if(!main)return;if(!document.getElementById('view-calendar'))main.insertAdjacentHTML('beforeend','<div id="view-calendar" class="view hidden"></div><div id="view-clients" class="view hidden"></div>')}
function addNotification(){const top=document.querySelector('.topbar');if(!top||document.getElementById('notify-btn'))return;const b=document.createElement('button');b.id='notify-btn';b.className='notify-button';b.type='button';b.innerHTML='🔔 <span id="notify-count">0</span>';b.title='Нові заявки';b.onclick=()=>document.querySelector('[data-view="appointments"]')?.click();top.appendChild(b)}
async function refreshNotification(){try{const a=await getAppointments(),n=a.filter(x=>x.status==='new').length;const el=document.getElementById('notify-count');if(el)el.textContent=n;const badge=document.getElementById('new-count');if(badge)badge.textContent=n}catch{}}
function enhancedNav(v){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const title=document.getElementById('page-title');if(title)title.textContent=v==='calendar'?'Календар':'Клієнти'}
async function showEnhanced(v){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));const target=document.getElementById('view-'+v);if(!target)return;target.classList.remove('hidden');enhancedNav(v);try{const a=await getAppointments();v==='calendar'?renderCalendar(a):renderClients(a)}catch(e){target.innerHTML=`<div class="card error">Помилка: ${esc(e.message)}</div>`}}
function parseMeta(x){if(x?.additional_services){try{const z=JSON.parse(x.additional_services);if(z&&typeof z==='object'&&!Array.isArray(z))return z}catch{}}return{services:Array.isArray(x?.selected_services)?x.selected_services:[]}}
function renderCalendar(a){const root=document.getElementById('view-calendar'),now=new Date();now.setHours(0,0,0,0);const end=new Date(now);end.setDate(end.getDate()+14);const upcoming=a.filter(x=>{const d=new Date(x.preferred_time);return !isNaN(d)&&d>=now&&d<end&&x.status!=='cancelled'}).sort((x,y)=>new Date(x.preferred_time)-new Date(y.preferred_time));const groups={};upcoming.forEach(x=>{const d=new Date(x.preferred_time),key=d.toLocaleDateString('uk-UA',{weekday:'long',day:'numeric',month:'long'});(groups[key]??=[]).push(x)});root.innerHTML=`<div class="toolbar"><div><h3>Найближчі 14 днів</h3><span style="color:#aaa">${upcoming.length} записів</span></div><button class="small-btn" id="cal-refresh">Оновити</button></div>${Object.keys(groups).length?Object.entries(groups).map(([day,items])=>`<div class="calendar-day"><h3>${esc(day)}</h3><div class="calendar-list">${items.map(x=>`<div class="card calendar-item"><div class="calendar-time">${esc(new Date(x.preferred_time).toLocaleTimeString('uk-UA',{hour:'2-digit',minute:'2-digit'}))}</div><div><b>${esc(x.pet_name)}</b><span>${esc(x.breed||'Без породи')} · ${esc(x.animal_type==='cat'?'Кіт':'Собака')}</span></div><div><b>${esc(x.owner_name||'—')}</b><span>${esc(x.owner_contact)}</span></div><div><span class="badge ${esc(x.status)}">${esc(({new:'Нова',confirmed:'Підтверджена',done:'Виконана'})[x.status]||x.status)}</span></div></div>`).join('')}</div></div>`).join(''):'<div class="card">На найближчі 14 днів записів немає.</div>'}`;const b=document.getElementById('cal-refresh');if(b)b.onclick=()=>showEnhanced('calendar')}
function openClientCard(client){const visits=[...client.visits].sort((a,b)=>new Date(b.preferred_time)-new Date(a.preferred_time));const pets=[...client.pets].sort((a,b)=>String(a).localeCompare(String(b),'uk'));const rows=visits.map(x=>{const m=parseMeta(x),svc=Array.isArray(m.services)?m.services.map(v=>typeof v==='string'?v:v.title).filter(Boolean).join(', '):'';return `<tr><td>${esc(fmt(x.preferred_time))}</td><td><b>${esc(x.pet_name||'—')}</b></td><td>${esc(x.breed||'—')}</td><td>${esc(m.coat_condition==='light'?'Є ковтуни':m.coat_condition==='severe'?'Сильні ковтуни':'Нормальна шерсть')}</td><td>${esc(svc||'—')}</td><td>${esc(m.estimated_total?m.estimated_total+' грн':'—')}</td><td>${esc(({new:'Нова',confirmed:'Підтверджена',done:'Виконана',cancelled:'Скасована'})[x.status]||x.status||'—')}</td><td>${esc(x.comment||'—')}</td></tr>`}).join('');const petsText=pets.length?pets.map(esc).join(', '):'—';const html=`<h3>Картка клієнта</h3><div class="card" style="margin-bottom:14px"><div style="display:grid;gap:8px"><div><b>Господар:</b> ${esc(client.name)}</div><div><b>Телефон:</b> ${esc(client.contact)}</div><div><b>Улюбленці:</b> ${petsText}</div><div><b>Візитів:</b> ${client.visits.length}</div><div><b>Останній запис:</b> ${esc(fmt(client.last))}</div></div></div><h4 style="margin:0 0 10px">Історія відвідувань</h4><div class="table-wrap"><table class="table"><thead><tr><th>Дата</th><th>Улюбленець</th><th>Порода</th><th>Стан шерсті</th><th>Послуги</th><th>Сума</th><th>Статус</th><th>Коментар</th></tr></thead><tbody>${rows||'<tr><td colspan="8">Історії ще немає.</td></tr>'}</tbody></table></div><div class="modal-actions"><button class="small-btn" onclick="closeModal()">Закрити</button></div>`;if(typeof window.modal==='function')window.modal(html)}
function renderClients(a){const root=document.getElementById('view-clients'),map=new Map();a.forEach(x=>{const key=(x.owner_contact||'').trim().toLowerCase()||x.id,old=map.get(key);if(!old)map.set(key,{name:x.owner_name||'—',contact:x.owner_contact||'—',pets:new Set([x.pet_name||'—']),visits:[x],last:x.preferred_time});else{if(old.name==='—'&&x.owner_name)old.name=x.owner_name;old.pets.add(x.pet_name||'—');old.visits.push(x);if(new Date(x.preferred_time)>new Date(old.last))old.last=x.preferred_time}});const clients=[...map.values()].sort((a,b)=>b.visits.length-a.visits.length);root.innerHTML=`<div class="toolbar"><div><h3>Клієнти</h3><span style="color:#aaa">${clients.length} контактів · натисніть на клієнта для повної картки</span></div><input id="client-search" placeholder="Пошук господаря, телефону або улюбленця"></div><div class="card table-wrap"><table class="table"><thead><tr><th>Господар</th><th>Телефон</th><th>Улюбленці</th><th>Візитів</th><th>Останній запис</th><th></th></tr></thead><tbody id="client-body">${clients.map((c,i)=>`<tr data-client-index="${i}" style="cursor:pointer"><td><b>${esc(c.name)}</b></td><td>${esc(c.contact)}</td><td>${[...c.pets].map(esc).join(', ')}</td><td>${c.visits.length}</td><td>${esc(fmt(c.last))}</td><td><button class="small-btn" type="button" data-client-open="${i}">Відкрити</button></td></tr>`).join('')||'<tr><td colspan="6">Клієнтів поки немає.</td></tr>'}</tbody></table></div>`;const search=document.getElementById('client-search');if(search)search.oninput=()=>{const q=search.value.toLowerCase();document.querySelectorAll('#client-body tr').forEach(tr=>tr.style.display=tr.textContent.toLowerCase().includes(q)?'':'none')};const body=document.getElementById('client-body');if(body)body.onclick=e=>{const row=e.target.closest('tr[data-client-index]');if(row)openClientCard(clients[Number(row.dataset.clientIndex)])}}
function boot(){addNav();addViews();addNotification();refreshNotification();setInterval(refreshNotification,60000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();