(()=>{
  const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const fmt=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d)?v:d.toLocaleString('uk-UA',{dateStyle:'short',timeStyle:'short'})};
  async function getAppointments(){const r=await fetch(API+'/appointments',{credentials:'include'});if(!r.ok)throw Error('Не вдалося отримати записи');return r.json()}
  function addNav(){const nav=document.querySelector('.sidebar nav');if(!nav||document.querySelector('[data-view="calendar"]'))return;nav.insertAdjacentHTML('beforeend','<button class="nav-item" data-view="calendar">▦ <span>Календар</span></button><button class="nav-item" data-view="clients">♙ <span>Клієнти</span></button>');['calendar','clients'].forEach(v=>{const b=document.querySelector(`[data-view="${v}"]`);b.onclick=()=>showEnhanced(v)})}
  function addViews(){const main=document.querySelector('.main');if(!main)return;if(!document.getElementById('view-calendar'))main.insertAdjacentHTML('beforeend','<div id="view-calendar" class="view hidden"></div><div id="view-clients" class="view hidden"></div>')}
  function addNotification(){const top=document.querySelector('.topbar');if(!top||document.getElementById('notify-btn'))return;const b=document.createElement('button');b.id='notify-btn';b.className='notify-button';b.type='button';b.innerHTML='🔔 <span id="notify-count">0</span>';b.title='Нові заявки';b.onclick=()=>{const n=document.querySelector('[data-view="appointments"]');if(n)n.click()};top.appendChild(b)}
  async function refreshNotification(){try{const a=await getAppointments();const n=a.filter(x=>x.status==='new').length;const el=document.getElementById('notify-count');if(el)el.textContent=n;const badge=document.getElementById('new-count');if(badge)badge.textContent=n}catch{}}
  function enhancedNav(v){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.getElementById('page-title').textContent=v==='calendar'?'Календар': 'Клієнти'}
  async function showEnhanced(v){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));document.getElementById('view-'+v).classList.remove('hidden');enhancedNav(v);try{const a=await getAppointments();v==='calendar'?renderCalendar(a):renderClients(a)}catch(e){document.getElementById('view-'+v).innerHTML=`<div class="card error">Помилка: ${esc(e.message)}</div>`}}
  function renderCalendar(a){const root=document.getElementById('view-calendar');const now=new Date();now.setHours(0,0,0,0);const end=new Date(now);end.setDate(end.getDate()+14);const upcoming=a.filter(x=>{const d=new Date(x.preferred_time);return !isNaN(d)&&d>=now&&d<end&&x.status!=='cancelled'}).sort((x,y)=>new Date(x.preferred_time)-new Date(y.preferred_time));const groups={};upcoming.forEach(x=>{const d=new Date(x.preferred_time);const key=d.toLocaleDateString('uk-UA',{weekday:'long',day:'numeric',month:'long'});(groups[key]??=[]).push(x)});root.innerHTML=`<div class="toolbar"><div><h3>Найближчі 14 днів</h3><span style="color:#aaa">${upcoming.length} записів</span></div><button class="small-btn" id="cal-refresh">Оновити</button></div>${Object.keys(groups).length?Object.entries(groups).map(([day,items])=>`<div class="calendar-day"><h3>${esc(day)}</h3><div class="calendar-list">${items.map(x=>`<div class="card calendar-item"><div class="calendar-time">${esc(new Date(x.preferred_time).toLocaleTimeString('uk-UA',{hour:'2-digit',minute:'2-digit'}))}</div><div><b>${esc(x.pet_name)}</b><span>${esc(x.breed||'Без породи')}</span></div><div>${esc(x.owner_contact)}</div><div><span class="badge ${esc(x.status)}">${esc(({new:'Нова',confirmed:'Підтверджена',done:'Виконана'})[x.status]||x.status)}</span></div></div>`).join('')}</div></div>`).join(''):'<div class="card">На найближчі 14 днів записів немає.</div>'}`;document.getElementById('cal-refresh').onclick=()=>showEnhanced('calendar')}
  function renderClients(a){const root=document.getElementById('view-clients');const map=new Map();a.forEach(x=>{const key=(x.owner_contact||'').trim().toLowerCase()||x.id;const old=map.get(key);if(!old)map.set(key,{contact:x.owner_contact||'—',pets:new Set([x.pet_name||'—']),visits:1,last:x.preferred_time});else{old.pets.add(x.pet_name||'—');old.visits++;if(new Date(x.preferred_time)>new Date(old.last))old.last=x.preferred_time}});const clients=[...map.values()].sort((a,b)=>b.visits-a.visits);root.innerHTML=`<div class="toolbar"><div><h3>Клієнти</h3><span style="color:#aaa">${clients.length} контактів · дані сформовані з історії записів</span></div><input id="client-search" placeholder="Пошук клієнта або улюбленця"></div><div class="card table-wrap"><table class="table"><thead><tr><th>Власник</th><th>Улюбленці</th><th>Візитів</th><th>Останній запис</th></tr></thead><tbody id="client-body">${clients.map(c=>`<tr><td><b>${esc(c.contact)}</b></td><td>${[...c.pets].map(esc).join(', ')}</td><td>${c.visits}</td><td>${esc(fmt(c.last))}</td></tr>`).join('')||'<tr><td colspan="4">Клієнтів поки немає.</td></tr>'}</tbody></table></div>`;const draw=()=>{const q=document.getElementById('client-search').value.toLowerCase();document.querySelectorAll('#client-body tr').forEach(tr=>tr.style.display=tr.textContent.toLowerCase().includes(q)?'':'none')};document.getElementById('client-search').oninput=draw}
  function boot(){addNav();addViews();addNotification();refreshNotification();setInterval(refreshNotification,60000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
