(()=>{
const pages=[['dashboard','🏠','Огляд'],['appointments','📋','Записи'],['calendar','📅','Календар'],['hours','🕐','Графік'],['reviews','⭐','Відгуки'],['services','✂','Послуги'],['clients','👥','Клієнти'],['home-editor','✏️','Головна'],['pricing','₴','Прайс']];
const root=()=>document.getElementById('rp-mobile-menu');
const navButton=v=>document.querySelector('.sidebar .nav-item[data-view="'+v+'"]');
function go(v){const b=navButton(v);if(b)b.click();else setTimeout(()=>{const x=navButton(v);if(x)x.click()},200);sync()}
function sync(){const r=root();if(!r)return;const active=document.querySelector('.sidebar .nav-item.active')?.dataset.view;r.querySelectorAll('[data-mobile-view]').forEach(b=>b.classList.toggle('active',b.dataset.mobileView===active));const n=Number(document.getElementById('new-count')?.textContent||0);const badge=r.querySelector('[data-mobile-count="appointments"]');if(badge){badge.hidden=!n;badge.textContent=String(n)}}
function build(){let r=root();if(!r){r=document.createElement('nav');r.id='rp-mobile-menu';document.body.appendChild(r)}let html='<div class="rp-mobile-menu-scroll">';pages.forEach(p=>{html+='<button class="rp-mobile-menu-item" type="button" data-mobile-view="'+p[0]+'"><span class="mi-icon">'+p[1]+'</span><span class="mi-label">'+p[2]+'</span><span class="mi-badge" data-mobile-count="'+p[0]+'" hidden></span></button>'});html+='<button class="rp-mobile-menu-item rp-mobile-menu-logout" type="button" data-mobile-logout="1"><span class="mi-icon">🚪</span><span class="mi-label">Вийти</span></button></div>';r.innerHTML=html;
const scroll=r.querySelector('.rp-mobile-menu-scroll');r.querySelectorAll('[data-mobile-view]').forEach(b=>b.onclick=()=>go(b.dataset.mobileView));r.querySelector('[data-mobile-logout]')?.addEventListener('click',()=>document.getElementById('logout')?.click());let down=false,startX=0,startScroll=0;scroll.addEventListener('pointerdown',e=>{down=true;startX=e.clientX;startScroll=scroll.scrollLeft;scroll.setPointerCapture?.(e.pointerId)});scroll.addEventListener('pointermove',e=>{if(down)scroll.scrollLeft=startScroll-(e.clientX-startX)});scroll.addEventListener('pointerup',()=>down=false);scroll.addEventListener('pointercancel',()=>down=false);window.rpMobileMenuSync=sync;sync()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build,{once:true});else build();
})();