(()=>{
  const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  function addNav(){const nav=document.querySelector('.sidebar nav');if(!nav||document.querySelector('[data-view="portfolio"]'))return;nav.insertAdjacentHTML('beforeend','<button class="nav-item" data-view="portfolio">▣ <span>Портфоліо</span></button>');nav.querySelector('[data-view="portfolio"]').addEventListener('click',show)}
  function addView(){const main=document.querySelector('.main');if(main&&!document.getElementById('view-portfolio'))main.insertAdjacentHTML('beforeend','<div id="view-portfolio" class="view hidden"></div>')}
  function focusManager(){const m=document.getElementById('portfolio-r2-manager');if(!m)return;m.scrollIntoView({behavior:'smooth',block:'start'});const f=m.querySelector('[data-new-album]');if(f)f.focus({preventScroll:true})}
  async function loadAlbums(){const r=await fetch(API+'/public/portfolio?ts='+Date.now(),{cache:'no-store'});let j=[];try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||`API ${r.status}`);return Array.isArray(j)?j:[]}
  async function show(){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));const root=document.getElementById('view-portfolio');if(!root)return;root.classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='portfolio'));const title=document.getElementById('page-title');if(title)title.textContent='Портфоліо';root.innerHTML='<div class="portfolio-admin-head"><div><h3>Портфоліо</h3><p>Альбоми, фото та відео робіт Royal Pet.</p></div><div class="portfolio-admin-actions"><a class="small-btn" href="../portfolio/" target="_blank" rel="noopener">Відкрити сторінку</a><button class="small-btn gold" id="focus-portfolio-editor" type="button">＋ Додати фото / відео</button></div></div><div class="card portfolio-admin-note"><b>Медіатека Cloudflare R2</b><span>Альбоми та матеріали керуються через новий Worker API. Форма нижче дозволяє створити альбом навіть до повторного deploy Worker з R2.</span></div><div id="portfolio-admin-list" class="portfolio-admin-list">Завантаження…</div>';document.getElementById('focus-portfolio-editor').onclick=focusManager;const list=document.getElementById('portfolio-admin-list');try{const albums=await loadAlbums();list.innerHTML=albums.length?albums.map(a=>`<div class="card portfolio-admin-album"><div><h4>${esc(a.title||'Без назви')}</h4><span>${Array.isArray(a.items)?a.items.length:0} матеріалів</span></div><div><span>${esc(a.description||'')}</span></div></div>`).join(''):'<div class="card">Альбомів поки немає. Створіть перший у формі нижче.</div>'}catch(e){list.innerHTML=`<div class="card error">${esc(e.message)}</div>`}setTimeout(focusManager,80)}
  function boot(){addNav();addView()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
