(()=>{
  const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const jsonHeaders=()=>({'Content-Type':'application/json'});
  const api=async(path,opts={})=>{const headers=new Headers(opts.headers||{});if(!(opts.body instanceof FormData)&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const r=await fetch(API+path,{...opts,credentials:'include',headers});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||`API ${r.status}`);return j};
  let albums=[];let health=null;
  const root=()=>document.getElementById('portfolio-r2-manager');
  async function healthCheck(){try{const r=await fetch(API+'/health?ts='+Date.now(),{cache:'no-store',credentials:'include'});const j=await r.json().catch(()=>({}));health={ok:r.ok,data:j,status:r.status};return health}catch(e){health={ok:false,data:{},status:0,error:e};return health}}
  async function loadAlbums(){albums=await api('/portfolio/albums?ts='+Date.now());return albums}
  function render(){const r=root();if(!r)return;const select=r.querySelector('[data-album-select]');select.innerHTML='<option value="">Оберіть альбом</option>'+albums.map(a=>`<option value="${esc(a.id)}">${esc(a.title)}</option>`).join('');const list=r.querySelector('[data-album-list]');list.innerHTML=albums.length?albums.map(a=>`<div class="portfolio-r2-album-row"><div><strong>${esc(a.title)}</strong><span>${esc(a.description||'')}</span></div><div class="portfolio-r2-actions"><button type="button" class="small-btn" data-open-album="${esc(a.id)}">Обрати</button><button type="button" class="small-btn danger" data-delete-album="${esc(a.id)}">Видалити</button></div></div>`).join(''):'<div class="card">Альбомів поки немає.</div>';list.querySelectorAll('[data-open-album]').forEach(b=>b.onclick=()=>{select.value=b.dataset.openAlbum;r.querySelector('[data-title]').focus()});list.querySelectorAll('[data-delete-album]').forEach(b=>b.onclick=async()=>{const a=albums.find(x=>x.id===b.dataset.deleteAlbum);if(!a||!confirm(`Видалити альбом «${a.title}» і всі його матеріали?`))return;try{await api('/portfolio/albums/'+encodeURIComponent(a.id),{method:'DELETE'});await loadAlbums();render()}catch(e){alert(e.message)}})}
  async function createAlbum(){const r=root(),title=r.querySelector('[data-new-album]').value.trim(),description=r.querySelector('[data-album-description]').value.trim();if(!title)return alert('Введіть назву нового альбому.');try{const out=await api('/portfolio/albums',{method:'POST',headers:jsonHeaders(),body:JSON.stringify({title,description,sort_order:albums.length,active:true})});await loadAlbums();render();r.querySelector('[data-album-select]').value=out.id;r.querySelector('[data-new-album]').value='';r.querySelector('[data-album-description]').value='';r.querySelector('[data-status]').textContent='Альбом створено ✓'}catch(e){alert(e.message)}}
  async function uploadFile(file,type){const endpoint=API+'/media/upload?type='+encodeURIComponent(type)+'&filename='+encodeURIComponent(file.name);const r=await fetch(endpoint,{method:'PUT',body:file,credentials:'include',headers:{'Content-Type':file.type,'Content-Length':String(file.size)}});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||`Помилка завантаження: ${r.status}`);return j}
  async function submit(e){e.preventDefault();const r=root(),files=[...r.querySelector('[data-files]').files];if(!files.length)return alert('Оберіть фото або відео.');if(!(health&&health.data&&health.data.r2Configured===true))return alert('R2 ще не підключений до опублікованої версії Worker.');r.querySelector('[data-submit]').disabled=true;r.querySelector('[data-status]').textContent='Завантаження…';try{const albumId=r.querySelector('[data-album-select]').value;if(!albumId)throw Error('Спочатку оберіть існуючий альбом або створіть новий.');const title=r.querySelector('[data-title]').value.trim(),desc=r.querySelector('[data-description]').value.trim(),cover=r.querySelector('[data-cover]').checked;let first=true;for(const file of files){const type=file.type.startsWith('video/')?'video':'image';const out=await uploadFile(file,type);await api('/portfolio/items',{method:'POST',headers:jsonHeaders(),body:JSON.stringify({album_id:albumId,type,title:title||file.name.replace(/\.[^.]+$/,''),description:desc,object_key:out.key,sort_order:Date.now(),active:true,set_cover:cover&&first})});first=false}r.querySelector('[data-files]').value='';r.querySelector('[data-title]').value='';r.querySelector('[data-description]').value='';r.querySelector('[data-cover]').checked=false;r.querySelector('[data-status]').textContent=`Додано матеріалів: ${files.length} ✓`;await loadAlbums();render()}catch(err){r.querySelector('[data-status]').textContent='';alert(err.message)}finally{r.querySelector('[data-submit]').disabled=false}}
  function inject(){const v=document.getElementById('view-portfolio');if(!v||document.getElementById('portfolio-r2-manager'))return;const box=document.createElement('div');box.id='portfolio-r2-manager';box.innerHTML='<div class="card portfolio-r2-card"><div class="portfolio-r2-head"><div><h3>Медіатека Cloudflare R2</h3><p>Створюйте альбоми, а потім додавайте фото та відео прямо з кабінету.</p></div><span class="portfolio-r2-status" data-status>Перевірка Worker…</span></div><form class="portfolio-r2-form"><div class="form-grid"><label>Існуючий альбом<select data-album-select><option value="">Завантаження…</option></select></label><label>Новий альбом<input data-new-album placeholder="Наприклад: До / Після"></label><label>Опис нового альбому<textarea data-album-description rows="2" placeholder="Короткий опис"></textarea></label><label>Назва роботи<input data-title placeholder="Наприклад: Мілка після грумінгу"></label><label>Опис роботи<textarea data-description rows="2" placeholder="Необов’язково"></textarea></label><label class="full">Файли<input data-files type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime" multiple><small>Фото до 15 МБ, відео до 100 МБ за один файл.</small></label><label class="portfolio-r2-check"><input data-cover type="checkbox"> Перший доданий файл зробити обкладинкою альбому</label></div><div class="modal-actions"><button class="small-btn" id="create-r2-album" type="button">＋ Створити альбом</button><button class="small-btn gold" data-submit type="submit">＋ Завантажити</button><span data-status></span></div></form></div><div class="portfolio-r2-list card"><h3>Альбоми</h3><div data-album-list>Завантаження…</div></div>';v.appendChild(box);const form=box.querySelector('form');form.addEventListener('submit',submit);box.querySelector('#create-r2-album').addEventListener('click',createAlbum);setTimeout(async()=>{const h=await healthCheck();try{await loadAlbums();render()}catch(e){box.querySelector('[data-album-list]').innerHTML=`<div class="card error">Не вдалося отримати альбоми: ${esc(e.message)}</div>`}if(h.ok&&h.data.r2Configured===true){box.querySelector('[data-status]').textContent='Worker + R2 підключені ✓';return}if(h.ok&&h.data.r2Configured===false){box.querySelector('[data-status]').textContent='Worker працює, але R2 не видно — потрібен redeploy Worker після binding MEDIA';return}box.querySelector('[data-status]').textContent=`Worker API недоступний (HTTP ${h.status||'—'})`},0)}
  const obs=new MutationObserver(inject);obs.observe(document.body,{childList:true,subtree:true});inject();
})();
