(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=v=>Number(v||0).toLocaleString('uk-UA');
const originalFetch=window.fetch.bind(window);
const numericPrice=v=>{const n=parseFloat(String(v??'').replace(',','.').replace(/[^0-9.\-]/g,''));return Number.isFinite(n)?n:0};
async function getServices(){const r=await originalFetch(API+'/services',{credentials:'include'});if(!r.ok)throw Error('Не вдалося завантажити прайс');return r.json()}
async function getSaved(){try{const r=await originalFetch(API+'/hours',{credentials:'include'});if(r.ok){const h=await r.json();if(h.__pricing__)return JSON.parse(h.__pricing__)||{services:{}}}}catch{}return{services:{}}}
async function savePricing(id,light,severe){const saved=await getSaved();saved.services=saved.services||{};const old=saved.services[id]||{};saved.services[id]={...old,light:Math.max(0,numericPrice(light)),severe:Math.max(0,numericPrice(severe))};delete saved.services[id].base;delete saved.services[id].none;const r=await originalFetch(API+'/hours',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({__pricing__:JSON.stringify(saved)})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`API ${r.status}`)}
function style(){if(document.getElementById('rp-price-editor-style'))return;const s=document.createElement('style');s.id='rp-price-editor-style';s.textContent=`#view-pricing .price-edit-grid{display:grid;gap:12px}#view-pricing .price-row{display:grid;grid-template-columns:minmax(220px,1.5fr) repeat(2,minmax(150px,1fr)) minmax(120px,auto);gap:12px;align-items:end;padding:16px;border:1px solid rgba(215,173,85,.14);border-radius:12px;background:rgba(255,255,255,.02)}#view-pricing .price-row input{width:100%;box-sizing:border-box}#view-pricing .price-label{font-weight:700;font-size:15px}#view-pricing .price-note{font-size:12px;color:#999;margin-top:4px;line-height:1.45}#view-pricing .price-input label{font-size:12px;color:#aaa;display:grid;gap:5px}#view-pricing .price-status{min-height:18px;font-size:12px;color:#8bd69a;margin-top:4px}@media(max-width:900px){#view-pricing .price-row{grid-template-columns:1fr 1fr}.price-row>div:first-child{grid-column:1/-1}.price-row button{width:100%}}@media(max-width:520px){#view-pricing .price-row{grid-template-columns:1fr}}`;document.head.appendChild(s)}
async function render(){style();document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));let root=document.getElementById('view-pricing');if(!root){root=document.createElement('div');root.id='view-pricing';root.className='view';document.querySelector('.main')?.appendChild(root)}root.classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view==='pricing'));const title=document.getElementById('page-title');if(title)title.textContent='Прайс';root.innerHTML='<div class="card">Завантаження доплат…</div>';try{const [services,saved]=await Promise.all([getServices(),getSaved()]);const p=saved.services||{};const rows=services.filter(s=>s.active!==false).map(s=>{const sp=p[s.id]||{};return `<div class="price-row" data-service="${esc(s.id)}"><div><div class="price-label">${esc(s.title)}</div><div class="price-note">Базова ціна цієї послуги не змінюється.</div></div><div class="price-input"><label>Ковтуни, + грн<input type="number" min="0" step="1" data-light value="${sp.light==null?'':numericPrice(sp.light)}" placeholder="Без доплати"></label></div><div class="price-input"><label>Сильні ковтуни, + грн<input type="number" min="0" step="1" data-severe value="${sp.severe==null?'':numericPrice(sp.severe)}" placeholder="Без доплати"></label></div><div><button class="small-btn gold" data-save-price="${esc(s.id)}">Зберегти доплати</button><div class="price-status" data-price-status></div></div></div>`}).join('');root.innerHTML=`<div class="toolbar"><div><h3>Доплати до прайсу</h3><span style="color:#aaa">Додавайте доплату за ковтуни лише там, де вона потрібна.</span></div><button class="small-btn" id="price-reload">Оновити</button></div><div class="card"><div class="price-edit-grid">${rows||'<div>Послуг поки немає.</div>'}</div><div class="price-note" style="margin-top:14px"><b>Важливо:</b> існуючі ціни послуг не редагуються і не змінюються. Доплати є окремими та необов’язковими.</div></div>`;root.querySelector('#price-reload').onclick=render;root.querySelectorAll('[data-save-price]').forEach(btn=>btn.onclick=async()=>{const row=btn.closest('.price-row'),status=row.querySelector('[data-price-status]');btn.disabled=true;status.textContent='Збереження…';try{await savePricing(btn.dataset.savePrice,row.querySelector('[data-light]').value,row.querySelector('[data-severe]').value);status.textContent='Доплати збережено ✓'}catch(e){status.textContent='Помилка: '+e.message}finally{btn.disabled=false}})}catch(e){root.innerHTML=`<div class="card error">Помилка: ${esc(e.message)}</div>`}}
function install(){const button=document.querySelector('[data-view="pricing"]');if(!button)return;if(button.dataset.priceEditorInstalled==='1')return;button.dataset.priceEditorInstalled='1';button.onclick=render}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
new MutationObserver(install).observe(document.body,{childList:true,subtree:true});
})();