(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)&&n>=0?n:0};
async function api(path,opts={}){const r=await fetch(API+path,{credentials:'include',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`API ${r.status}`);return j}
async function getSaved(){try{const h=await api('/hours');return h?.__pricing__?JSON.parse(h.__pricing__)||{services:{}}:{services:{}}}catch{return{services:{}}}}
async function saveSurcharge(id,light,severe){const saved=await getSaved();saved.services=saved.services||{};saved.services[id]={...(saved.services[id]||{}),light:num(light),severe:num(severe)};await api('/hours',{method:'PUT',body:JSON.stringify({__pricing__:JSON.stringify(saved)})})}
function styles(){if(document.getElementById('rp-price-add-style'))return;const s=document.createElement('style');s.id='rp-price-add-style';s.textContent=`#view-pricing .price-add-card{margin-top:16px;padding:18px;border:1px solid rgba(215,173,85,.2);border-radius:14px;background:rgba(215,173,85,.04)}#view-pricing .price-add-grid{display:grid;grid-template-columns:1.2fr 1.6fr 1fr 1fr auto;gap:10px;align-items:end}#view-pricing .price-add-grid label{display:grid;gap:6px;font-size:12px;color:#aaa}#view-pricing .price-add-grid input,#view-pricing .price-add-grid textarea{width:100%;box-sizing:border-box}#view-pricing .price-add-grid textarea{min-height:42px;resize:vertical}#view-pricing .price-add-status{margin-top:10px;font-size:12px;min-height:18px}@media(max-width:900px){#view-pricing .price-add-grid{grid-template-columns:1fr 1fr}.price-add-grid label:first-child,.price-add-grid label:nth-child(2){grid-column:1/-1}.price-add-grid button{grid-column:1/-1}}@media(max-width:520px){#view-pricing .price-add-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
async function addService(title,description,price,light,severe){const j=await api('/services',{method:'POST',body:JSON.stringify({title,description,price:String(price),duration:'',category:'',image:'',active:true,order:999})});if(j.id&&(num(light)>0||num(severe)>0))await saveSurcharge(j.id,light,severe);return j}
function refresh(){setTimeout(()=>{window.renderPricing?.();},150)}
function renderAdd(){const root=document.getElementById('view-pricing');if(!root||root.querySelector('.price-add-card'))return;styles();const card=document.createElement('div');card.className='price-add-card';card.innerHTML='<h3 style="margin-top:0">Додати послугу в прайс</h3><div class="price-add-grid"><label>Назва<input id="price-new-title" placeholder="Наприклад, Чистка вух"></label><label>Опис<textarea id="price-new-description" placeholder="Короткий опис послуги"></textarea></label><label>Ціна, грн<input id="price-new-price" type="number" min="0" step="1" placeholder="0"></label><label>Ковтуни, + грн<input id="price-new-light" type="number" min="0" step="1" placeholder="0"></label><label>Сильні ковтуни, + грн<input id="price-new-severe" type="number" min="0" step="1" placeholder="0"></label><button class="small-btn gold" id="price-new-save">＋ Додати</button></div><div class="price-add-status" id="price-new-status"></div>';root.appendChild(card);card.querySelector('#price-new-save').onclick=async()=>{const status=card.querySelector('#price-new-status'),title=card.querySelector('#price-new-title').value.trim(),description=card.querySelector('#price-new-description').value.trim(),price=num(card.querySelector('#price-new-price').value),light=num(card.querySelector('#price-new-light').value),severe=num(card.querySelector('#price-new-severe').value);if(!title)return status.textContent='Вкажіть назву послуги';if(!Number.isFinite(price)||price<0)return status.textContent='Вкажіть коректну ціну';const btn=card.querySelector('#price-new-save');btn.disabled=true;status.textContent='Додавання…';try{await addService(title,description,price,light,severe);status.textContent='Послугу додано ✓';card.querySelector('#price-new-title').value='';card.querySelector('#price-new-description').value='';card.querySelector('#price-new-price').value='';card.querySelector('#price-new-light').value='';card.querySelector('#price-new-severe').value='';refresh()}catch(e){status.textContent='Помилка: '+e.message}finally{btn.disabled=false}}}
function install(){renderAdd()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();new MutationObserver(install).observe(document.body,{childList:true,subtree:true});
})();