(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function styles(){if(document.getElementById('rp-price-add-style'))return;const s=document.createElement('style');s.id='rp-price-add-style';s.textContent=`#view-pricing .price-add-card{margin-top:16px;padding:18px;border:1px solid rgba(215,173,85,.2);border-radius:14px;background:rgba(215,173,85,.04)}#view-pricing .price-add-grid{display:grid;grid-template-columns:1.5fr 1fr 1fr 1fr auto;gap:10px;align-items:end}#view-pricing .price-add-grid label{display:grid;gap:6px;font-size:12px;color:#aaa}#view-pricing .price-add-grid input{width:100%;box-sizing:border-box}#view-pricing .price-add-status{margin-top:10px;font-size:12px;min-height:18px}#view-pricing .price-add-note{margin-top:8px;color:#999;font-size:12px}@media(max-width:900px){#view-pricing .price-add-grid{grid-template-columns:1fr 1fr}.price-add-grid label:first-child{grid-column:1/-1}.price-add-grid button{grid-column:1/-1}}`;document.head.appendChild(s)}
async function getServices(){const r=await fetch(API+'/services',{credentials:'include',cache:'no-store'});if(!r.ok)throw Error('Не вдалося завантажити послуги');return r.json()}
async function addService(title,price){const r=await fetch(API+'/services',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,price:String(price),duration:'',category:'',description:'',image:'',active:true,order:999})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`API ${r.status}`);return j}
async function renderAdd(){const root=document.getElementById('view-pricing');if(!root||root.querySelector('.price-add-card'))return;styles();const card=document.createElement('div');card.className='price-add-card';card.innerHTML='<h3 style="margin-top:0">Додати пункт прайсу</h3><div class="price-add-grid"><label>Назва послуги<input id="price-new-title" placeholder="Наприклад, Чистка вух"></label><label>Мала, грн<input id="price-new-small" type="number" min="0" step="1" placeholder="0"></label><label>Середня, грн<input id="price-new-medium" type="number" min="0" step="1" placeholder="0"></label><label>Велика, грн<input id="price-new-large" type="number" min="0" step="1" placeholder="0"></label><button class="small-btn gold" id="price-new-save">＋ Додати</button></div><div class="price-add-note">Після додавання нова послуга одразу з’явиться в прайсі та буде доступна для вибору під час запису.</div><div class="price-add-status" id="price-new-status"></div>';root.appendChild(card);card.querySelector('#price-new-save').onclick=async()=>{const st=card.querySelector('#price-new-status'),title=card.querySelector('#price-new-title').value.trim(),vals=['small','medium','large'].map(k=>Number(card.querySelector('#price-new-'+k).value));if(!title)return st.textContent='Вкажіть назву послуги';if(vals.some(v=>!Number.isFinite(v)||v<0))return st.textContent='Вкажіть коректні ціни';const price=vals[1]||vals[0]||vals[2]||0;const btn=card.querySelector('#price-new-save');btn.disabled=true;st.textContent='Додавання…';try{await addService(title,price);st.textContent='Додано ✓';card.querySelectorAll('input').forEach(i=>i.value='');window.dispatchEvent(new CustomEvent('royalpet-price-added'));setTimeout(()=>{const b=document.querySelector('[data-view="pricing"]');if(b)b.click()},300)}catch(e){st.textContent='Помилка: '+e.message}finally{btn.disabled=false}}}
function install(){const root=document.getElementById('view-pricing');if(root)renderAdd()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();new MutationObserver(install).observe(document.body,{childList:true,subtree:true});
})();