(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)&&n>=0?n:0};
const money=v=>num(v).toLocaleString('uk-UA');
let services=[];let pricing={services:{}};
async function api(path,opts={}){const r=await fetch(API+path,{credentials:'include',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`API ${r.status}`);return j}
async function load(){const [s,h]=await Promise.all([api('/services').catch(()=>[]),api('/hours').catch(()=>({}))]);services=(Array.isArray(s)?s:[]).filter(x=>x.active!==false);try{pricing=h?.__pricing__?JSON.parse(h.__pricing__)||{services:{}}:{services:{}}}catch{pricing={services:{}}}}
async function savePricing(){await api('/hours',{method:'PUT',body:JSON.stringify({__pricing__:JSON.stringify(pricing)})})}
function css(){if(document.getElementById('rp-price-page-css'))return;const s=document.createElement('style');s.id='rp-price-page-css';s.textContent=`#view-pricing{padding-bottom:32px}.rp-head{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:20px}.rp-head h3{margin:0 0 5px;font-size:25px}.rp-head p{margin:0;color:#aaa;font-size:13px}.rp-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.rp-card{padding:18px;border:1px solid rgba(255,255,255,.09);border-radius:15px;background:rgba(255,255,255,.025)}.rp-card-top{display:flex;justify-content:space-between;gap:12px}.rp-name{font-size:18px;font-weight:700}.rp-price{font-size:20px;font-weight:700;white-space:nowrap}.rp-desc{margin-top:7px;color:#aaa;font-size:13px;line-height:1.45}.rp-extras{display:flex;flex-wrap:wrap;gap:7px;margin-top:12px}.rp-badge{padding:6px 9px;border-radius:8px;background:rgba(215,173,85,.09);color:#d7ad55;font-size:11px}.rp-actions{display:flex;gap:8px;margin-top:16px}.rp-actions button{flex:1}.rp-form{margin-bottom:18px;padding:18px;border:1px solid rgba(215,173,85,.25);border-radius:15px;background:rgba(215,173,85,.045)}.rp-grid{display:grid;grid-template-columns:1.2fr 1.5fr .8fr .9fr .9fr auto;gap:10px;align-items:end}.rp-grid label{display:grid;gap:6px;font-size:12px;color:#aaa}.rp-grid input,.rp-grid textarea{width:100%;box-sizing:border-box}.rp-grid textarea{min-height:42px;resize:vertical}.rp-form-actions{display:flex;gap:8px}.rp-status{min-height:18px;margin-top:9px;font-size:12px;color:#aaa}.rp-empty{padding:30px;text-align:center;color:#aaa;border:1px dashed rgba(255,255,255,.13);border-radius:14px;grid-column:1/-1}@media(max-width:1000px){.rp-list{grid-template-columns:1fr}.rp-grid{grid-template-columns:1fr 1fr}.rp-grid label:nth-child(1),.rp-grid label:nth-child(2){grid-column:1/-1}.rp-form-actions{grid-column:1/-1}}@media(max-width:560px){.rp-head{align-items:flex-start;flex-direction:column}.rp-grid{grid-template-columns:1fr}.rp-grid label{grid-column:1!important}.rp-card-top{flex-direction:column}.rp-price{white-space:normal}.rp-actions{flex-direction:column}}`;document.head.appendChild(s)}
function root(){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));const r=document.getElementById('view-pricing');r.classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view==='pricing'));const t=document.getElementById('page-title');if(t)t.textContent='Прайс';return r}
function form(item=null){const p=item?pricing.services?.[item.id]||{}:{};return `<div class="rp-form"><h3 style="margin-top:0">${item?'Редагування послуги':'Додати послугу'}</h3><div class="rp-grid"><label>Назва<input id="rp-title" value="${esc(item?.title||'')}" placeholder="Наприклад, Стрижка"></label><label>Опис<textarea id="rp-description" placeholder="Короткий опис">${esc(item?.description||'')}</textarea></label><label>Ціна, грн<input id="rp-price" type="number" min="0" step="1" value="${item?.price??''}" placeholder="0"></label><label>Ковтуни, + грн<input id="rp-light" type="number" min="0" step="1" value="${p.light>0?p.light:''}" placeholder="за необхідності"></label><label>Сильні ковтуни, + грн<input id="rp-severe" type="number" min="0" step="1" value="${p.severe>0?p.severe:''}" placeholder="за необхідності"></label><div class="rp-form-actions"><button class="small-btn gold" id="rp-save">${item?'Зберегти':'＋ Додати'}</button><button class="small-btn" id="rp-cancel">Скасувати</button></div></div><div class="rp-status" id="rp-status"></div></div>`}
async function save(item){const status=document.getElementById('rp-status'),btn=document.getElementById('rp-save'),title=document.getElementById('rp-title').value.trim(),description=document.getElementById('rp-description').value.trim(),price=num(document.getElementById('rp-price').value),light=num(document.getElementById('rp-light').value),severe=num(document.getElementById('rp-severe').value);if(!title)return status.textContent='Вкажіть назву послуги.';if(price<=0)return status.textContent='Вкажіть ціну послуги.';btn.disabled=true;status.textContent='Збереження…';try{let id=item?.id;if(item){await api('/services/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({title,description,price:String(price),active:true})})}else{id=(await api('/services',{method:'POST',body:JSON.stringify({title,description,price:String(price),duration:'',category:'',image:'',active:true,order:999})})).id}pricing.services=pricing.services||{};pricing.services[id]={...(pricing.services[id]||{}),light,severe};if(!light&&!severe){delete pricing.services[id].light;delete pricing.services[id].severe}await savePricing();await render()}catch(e){status.textContent='Помилка: '+e.message;btn.disabled=false}}
async function remove(item){if(!confirm(`Видалити послугу «${item.title}»?\n\nВона зникне з прайсу та форми запису.`))return;try{await api('/services/'+encodeURIComponent(item.id),{method:'PATCH',body:JSON.stringify({active:false})});if(pricing.services?.[item.id])delete pricing.services[item.id];await savePricing();await render()}catch(e){alert('Не вдалося видалити послугу: '+e.message)}}
async function render(editItem=null){css();const r=root();await load();r.innerHTML=`<div class="rp-head"><div><h3>Прайс послуг</h3><p>Створюйте послуги та за необхідності додавайте доплату за ковтуни.</p></div><button class="small-btn gold" id="rp-add">＋ Додати послугу</button></div>${editItem?form(editItem):''}<div class="rp-list" id="rp-list"></div>`;if(editItem){document.getElementById('rp-cancel').onclick=()=>render();document.getElementById('rp-save').onclick=()=>save(editItem)}document.getElementById('rp-add').onclick=()=>render({});const list=document.getElementById('rp-list');if(!services.length){list.innerHTML='<div class="rp-empty">Послуг ще немає. Натисніть «Додати послугу».</div>';return}list.innerHTML=services.map(v=>{const p=pricing.services?.[v.id]||{};return `<article class="rp-card"><div class="rp-card-top"><div class="rp-name">${esc(v.title)}</div><div class="rp-price">${money(v.price)} грн</div></div>${v.description?`<div class="rp-desc">${esc(v.description)}</div>`:''}<div class="rp-extras">${p.light>0?`<span class="rp-badge">Ковтуни: +${money(p.light)} грн</span>`:''}${p.severe>0?`<span class="rp-badge">Сильні ковтуни: +${money(p.severe)} грн</span>`:''}</div><div class="rp-actions"><button class="small-btn" data-edit="${esc(v.id)}">✎ Редагувати</button><button class="small-btn" data-delete="${esc(v.id)}">Видалити</button></div></article>`}).join('');list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>render(services.find(v=>String(v.id)===String(b.dataset.edit))));list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(services.find(v=>String(v.id)===String(b.dataset.delete))))}
window.renderPricing=render;document.addEventListener('click',e=>{const b=e.target.closest?.('[data-view="pricing"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();render()},true);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',css,{once:true});else css();
})();
