(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=v=>Number(v||0).toLocaleString('uk-UA');
let state=null;
async function loadData(){if(state)return state;const [breeds,pricing,svc]=await Promise.all([
 fetch('../content/breeds.json?pricing='+Date.now()).then(r=>r.json()).catch(()=>({dog:[],cat:[]})),
 fetch('../content/service-pricing.json?pricing='+Date.now()).then(r=>r.json()).catch(()=>({categories:{small:'Мала',medium:'Середня',large:'Велика'},coat_conditions:{none:{label:'Шерсть у нормальному стані'},light:{label:'Є ковтуни'},severe:{label:'Сильні ковтуни / запущена шерсть'}},services:{}})),
 fetch(API+'/services',{credentials:'include'}).then(r=>r.ok?r.json():[]).catch(()=>[])
]);
state={breeds,pricing,services:(Array.isArray(svc)?svc:[]).filter(x=>x.active!==false)};return state}
function readMeta(x){let raw=x?.additional_services||'';if(raw){try{const o=JSON.parse(raw);if(o&&typeof o==='object'&&!Array.isArray(o))return o}catch{}}
return{services:[],coat_condition:'none',breed_category:'',estimated_total:0,final_price:'',animal_type:x?.animal_type||'',breed:x?.breed||'',notes:raw};}
function categoryFor(s,animal,breed,stored){const list=s.breeds?.[animal]||[];const hit=list.find(x=>x.name===breed);return hit?.category||stored||'medium'}
function priceFor(svc,cat,cond,pricing){const p=pricing.services?.[svc.id];return p?Number(p[cat]||0)+Number(p[cond]||0):Number(svc.price||0)}
function injectStyles(){if(document.getElementById('royal-pricing-styles'))return;const s=document.createElement('style');s.id='royal-pricing-styles';s.textContent=`
.rp-pricing-box{display:grid;gap:12px;margin-top:14px;padding:16px;border:1px solid rgba(215,173,85,.28);border-radius:14px;background:rgba(215,173,85,.045)}
.rp-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.rp-grid label{display:grid;gap:6px}
.rp-grid .full{grid-column:1/-1}.rp-grid select,.rp-grid input{width:100%;box-sizing:border-box}
.rp-services{display:grid;gap:7px;max-height:230px;overflow:auto;padding:8px;border:1px solid rgba(215,173,85,.18);border-radius:10px}
.rp-service{display:flex;align-items:center;gap:10px;padding:8px;border-radius:8px}.rp-service:hover{background:rgba(215,173,85,.06)}.rp-service small{margin-left:auto;opacity:.8}
.rp-summary{display:grid;gap:6px;padding:12px;border-radius:10px;background:#151515}.rp-summary strong{font-size:1.2rem}.rp-final{font-size:1.25rem;color:#d7ad55}
.rp-help{font-size:.82rem;opacity:.68}.rp-note{font-size:.84rem;opacity:.72}
@media(max-width:700px){.rp-grid{grid-template-columns:1fr}.rp-grid .full{grid-column:auto}}
`;document.head.appendChild(s)}
function options(list,selected,placeholder){return `<option value="">${esc(placeholder)}</option>`+(list||[]).map(x=>`<option value="${esc(x.value||x.name)}" ${String(selected||'')===String(x.value||x.name)?'selected':''} data-category="${esc(x.category||'')}" data-id="${esc(x.id||'')}">${esc(x.label||x.name)}</option>`).join('')}
async function enhancedAppointment(x){
 injectStyles();const s=await loadData();const meta=readMeta(x||{});const animal=x?.animal_type||meta.animal_type||'';const breed=x?.breed||meta.breed||'';let category=categoryFor(s,animal,breed, x?.breed_category||meta.breed_category||'medium');
 const serviceIds=(Array.isArray(meta.services)?meta.services:[]).map(v=>String(v?.id??v));
 const fresh=!x;
 const animalOpts=`<option value="">Оберіть тип тварини</option><option value="dog" ${animal==='dog'?'selected':''}>Собака</option><option value="cat" ${animal==='cat'?'selected':''}>Кіт</option>`;
 const catLabels=s.pricing.categories||{small:'Мала',medium:'Середня',large:'Велика'};
 const coat=s.pricing.coat_conditions||{none:{label:'Шерсть у нормальному стані'},light:{label:'Є ковтуни'},severe:{label:'Сильні ковтуни / запущена шерсть'}};
 modal(`<h3>${fresh?'Новий запис':'Редагування запису'}</h3><div class="form-grid">
 <label>Ім’я улюбленця<input id="rp-pet" value="${esc(x?.pet_name||'')}"></label>
 <label>Вік<input id="rp-age" value="${esc(x?.age||'')}"></label>
 <label>Тип тварини<select id="rp-animal" required>${animalOpts}</select></label>
 <label>Порода<select id="rp-breed" required>${options(s.breeds?.[animal]||[],breed,'Оберіть породу')}</select><span class="rp-help">Порода автоматично визначає категорію.</span></label>
 <label id="rp-cat-wrap" class="${(s.breeds?.[animal]||[]).find(q=>q.name===breed)?.category==='other'?'':'hidden'}">Категорія<select id="rp-category">${options(Object.entries(catLabels).map(([value,label])=>({value,label})),category,'Оберіть категорію')}</select></label>
 <label>Ім’я господаря<input id="rp-owner" value="${esc(x?.owner_name||'')}"></label>
 <label>Контакт господаря<input id="rp-contact" value="${esc(x?.owner_contact||'')}"></label>
 <label>Бажаний час<input id="rp-time" type="datetime-local" value="${x?.preferred_time?new Date(x.preferred_time).toISOString().slice(0,16):''}"></label>
 <label>Останній грумінг<input id="rp-last" value="${esc(x?.last_grooming||'')}"></label>
 <label>Стан шерсті<select id="rp-coat">${Object.entries(coat).map(([v,o])=>`<option value="${esc(v)}" ${String(meta.coat_condition||'none')===v?'selected':''}>${esc(o.label)}</option>`).join('')}</select></label>
 <label class="full">Послуги</label><div class="rp-services full" id="rp-services">${s.services.map(v=>{const id=String(v.id),price=priceFor(v,category,meta.coat_condition||'none',s.pricing);return `<label class="rp-service"><input type="checkbox" value="${esc(id)}" ${serviceIds.includes(id)?'checked':''}><span>${esc(v.title)}</span><small data-price-for="${esc(id)}">${money(price)} грн</small></label>`}).join('')||'<span class="rp-help">Послуг поки немає.</span>'}</div>
 <label class="full">Фінальна ціна після огляду<input id="rp-final" type="number" min="0" step="1" value="${esc(meta.final_price??'')}" placeholder="Залиште порожнім, щоб використати орієнтовну"></label>
 <label class="full">Коментар<textarea id="rp-comment" rows="4">${esc(x?.comment||'')}</textarea></label>
 </div><div class="rp-pricing-box" id="rp-box"><div id="rp-lines"></div><div class="rp-summary"><div>Орієнтовно: <strong id="rp-estimate">0 грн</strong></div><div>До оплати: <strong class="rp-final" id="rp-pay">0 грн</strong></div><div class="rp-note">Орієнтовна сума автоматично рахується за породою, послугами та станом шерсті. Фінальна ціна встановлюється після огляду.</div></div></div><div class="modal-actions"><button class="small-btn" onclick="closeModal()">Скасувати</button><button class="small-btn gold" id="rp-save">${fresh?'Створити':'Зберегти'}</button></div>`);
 const animalEl=document.getElementById('rp-animal'),breedEl=document.getElementById('rp-breed'),catEl=document.getElementById('rp-category'),catWrap=document.getElementById('rp-cat-wrap'),coatEl=document.getElementById('rp-coat'),finalEl=document.getElementById('rp-final');
 const selected=()=>[...document.querySelectorAll('#rp-services input[type=checkbox]:checked')];
 const refresh=()=>{const breedObj=(s.breeds?.[animalEl.value]||[]).find(v=>v.name===breedEl.value);const cat=breedObj?.category||catEl.value||category||'medium';catWrap.classList.toggle('hidden',breedObj?.category!=='other');if(breedObj?.category&&breedObj.category!=='other')catEl.value=breedObj.category;const services=selected().map(ch=>s.services.find(v=>String(v.id)===String(ch.value))).filter(Boolean).map(v=>({id:v.id,title:v.title,price:priceFor(v,cat,coatEl.value,s.pricing)}));const est=services.reduce((n,v)=>n+Number(v.price||0),0);const manual=finalEl.value.trim();document.getElementById('rp-estimate').textContent=`${money(est)} грн`;document.getElementById('rp-pay').textContent=`${money(manual===''?est:Number(manual))} грн`;document.getElementById('rp-lines').innerHTML=services.length?services.map(v=>`<div>${esc(v.title)} — ${money(v.price)} грн</div>`).join(''):'<div class="rp-help">Послуги не обрані.</div>';document.querySelectorAll('[data-price-for]').forEach(el=>{const v=s.services.find(q=>String(q.id)===String(el.dataset.priceFor));if(v)el.textContent=`${money(priceFor(v,cat,coatEl.value,s.pricing))} грн`});return{cat,services,est}};
 animalEl.onchange=()=>{const list=s.breeds?.[animalEl.value]||[];breedEl.innerHTML=options(list,'','Оберіть породу');catWrap.classList.add('hidden');refresh()};breedEl.onchange=refresh;catEl.onchange=refresh;coatEl.onchange=refresh;finalEl.oninput=refresh;document.querySelectorAll('#rp-services input').forEach(v=>v.onchange=refresh);refresh();
 document.getElementById('rp-save').onclick=async()=>{const d={pet_name:document.getElementById('rp-pet').value.trim(),age:document.getElementById('rp-age').value.trim(),animal_type:animalEl.value,breed:breedEl.value,breed_category:catEl.value,owner_name:document.getElementById('rp-owner').value.trim(),owner_contact:document.getElementById('rp-contact').value.trim(),preferred_time:document.getElementById('rp-time').value,last_grooming:document.getElementById('rp-last').value,comment:document.getElementById('rp-comment').value};if(!d.pet_name||!d.owner_name||!d.owner_contact)return alert('Вкажіть ім’я улюбленця, господаря та контакт.');const calc=refresh();const old=readMeta(x||{});const metaOut={...old,animal_type:d.animal_type,breed:d.breed,breed_category:calc.cat,coat_condition:coatEl.value,services:calc.services,selected_services:calc.services.map(v=>v.id),estimated_total:calc.est,final_price:finalEl.value.trim()===''?null:Number(finalEl.value),updated_at:new Date().toISOString()};d.additional_services=JSON.stringify(metaOut);try{await (window.api?window.api:null);const endpoint=fresh?'/appointments':'/appointments/'+encodeURIComponent(x.id);const r=await fetch(API+endpoint,{method:fresh?'POST':'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`API ${r.status}`);closeModal();if(typeof window.renderAppointments==='function')window.renderAppointments();if(typeof window.dashboard==='function')window.dashboard()}catch(e){alert(e.message)}};
}
function install(){if(window.__royalPricingInstalled)return;window.__royalPricingInstalled=true;injectStyles();const originalShow=window.showAppointment;if(typeof originalShow==='function')window.showAppointment=enhancedAppointment;
 const nav=document.querySelector('.sidebar nav');if(nav&&!document.querySelector('[data-view="pricing"]')){nav.insertAdjacentHTML('beforeend','<button class="nav-item" data-view="pricing">₴ <span>Прайс</span></button>');const btn=nav.querySelector('[data-view="pricing"]');btn.onclick=showPricing}
}
async function showPricing(){install();document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));let root=document.getElementById('view-pricing');if(!root){root=document.createElement('div');root.id='view-pricing';root.className='view';document.querySelector('.main')?.appendChild(root)}document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='pricing'));document.getElementById('page-title').textContent='Прайс';const s=await loadData();const cat=s.pricing.categories||{};const coat=s.pricing.coat_conditions||{};root.innerHTML=`<div class="toolbar"><div><h3>Прайс за породою</h3><span style="color:#aaa">Категорія породи + стан шерсті + обрані послуги.</span></div><a class="small-btn gold" href="../admin/" target="_blank" rel="noopener">Відкрити CMS</a></div><div class="card"><p style="color:#aaa;margin-top:0">У прайсі нижче показані поточні значення з <code>content/service-pricing.json</code>. Сам прайс редагується через CMS. Ціни, зафіксовані в записі, зберігаються окремо і не змінюються при майбутній зміні прайсу.</p><div class="table-wrap"><table class="table"><thead><tr><th>Послуга</th><th>${esc(cat.small||'Мала')}</th><th>${esc(cat.medium||'Середня')}</th><th>${esc(cat.large||'Велика')}</th><th>Ковтуни</th><th>Сильні ковтуни</th></tr></thead><tbody>${s.services.map(v=>{const p=s.pricing.services?.[v.id]||{};return `<tr><td><b>${esc(v.title)}</b></td><td>${money(p.small??v.price)} грн</td><td>${money(p.medium??v.price)} грн</td><td>${money(p.large??v.price)} грн</td><td>+${money(p.light||0)} грн</td><td>+${money(p.severe||0)} грн</td></tr>`}).join('')}</tbody></table></div><div style="margin-top:14px;display:grid;gap:6px">${Object.entries(coat).map(([k,v])=>`<div><b>${esc(v.label)}</b> — ${esc(v.note||'')}</div>`).join('')}</div></div>`}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
