(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const CATEGORIES={complex:'Комплекс',hygiene:'Гігієна',adaptive:'Адаптивний грумінг',additional:'Додаткові послуги'};
const KEYS=Object.keys(CATEGORIES);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>{const m=String(v??'').replace(',','.').match(/\d+(?:\.\d+)?/);const n=m?Number(m[0]):0;return Number.isFinite(n)&&n>=0?n:0};
function categoryOf(x){const c=String(x?.category||'').trim().toLowerCase();if(KEYS.includes(c))return c;if(x?.id==='service-1')return'complex';if(x?.id==='service-2'||x?.id==='service-3')return'hygiene';if(x?.id==='service-4')return'adaptive';return'additional'}
async function api(path,opts={}){const r=await fetch(API+path,{credentials:'include',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`API ${r.status}`);return j}
function styles(){if(document.getElementById('rp-services-style'))return;const s=document.createElement('style');s.id='rp-services-style';s.textContent=`#view-services .cat-tabs{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:18px}.cat-tab{min-height:46px;border:1px solid rgba(255,255,255,.1);border-radius:12px;background:#111;color:#bbb;cursor:pointer;font:inherit;padding:9px}.cat-tab.active{border-color:#d7ad55;background:rgba(215,173,85,.11);color:#f2d789}.svc-list{display:grid;gap:12px}.svc-card{padding:18px 20px;border:1px solid rgba(255,255,255,.08);border-radius:15px;background:rgba(255,255,255,.025)}.svc-top{display:flex;justify-content:space-between;gap:15px;align-items:flex-start}.svc-name{font-size:18px;font-weight:700}.svc-cat{margin-top:4px;color:#d7ad55;font-size:12px}.svc-desc{margin-top:6px;color:#aaa;font-size:13px;line-height:1.5}.svc-price{font-size:21px;font-weight:700;white-space:nowrap}.svc-actions{display:flex;gap:8px;margin-top:15px;flex-wrap:wrap}.svc-delete{border:1px solid rgba(220,80,80,.35);background:transparent;color:#e58b8b}.cat-empty{padding:24px;border:1px solid rgba(255,255,255,.08);border-radius:15px;color:#aaa}.svc-head{display:flex;justify-content:space-between;align-items:flex-start;gap:15px;margin-bottom:18px}.svc-head h3{margin:0 0 5px;font-size:25px}.svc-head p{margin:0;color:#aaa;font-size:13px}@media(max-width:850px){#view-services .cat-tabs{grid-template-columns:1fr 1fr}}@media(max-width:600px){#view-services .cat-tabs{grid-template-columns:1fr}.svc-top{flex-direction:column}.svc-price{white-space:normal}.svc-head{flex-direction:column}}`;document.head.appendChild(s)}
function openEditor(item){const isEdit=!!item?.id,category=categoryOf(item),title=item?.title||'',price=num(item?.price),description=item?.description||'';modal(`<h3>${isEdit?'Редагувати позицію':'Додати позицію'}</h3><div class="form-grid"><label>Розділ<select id="svc-category">${KEYS.map(k=>`<option value="${k}" ${k===category?'selected':''}>${CATEGORIES[k]}</option>`).join('')}</select></label><label>Назва породи / послуги<input id="svc-title" value="${esc(title)}" placeholder="Наприклад, Мальтіпу"></label><label>Ціна, грн<input id="svc-price" type="number" min="0" step="1" value="${price||''}" placeholder="Наприклад, 1200"></label><label>Опис (необов’язково)<textarea id="svc-desc" rows="3" placeholder="Короткий опис">${esc(description)}</textarea></label></div><div class="modal-actions"><button class="small-btn" onclick="closeModal()">Скасувати</button><button class="small-btn gold" id="svc-save">${isEdit?'Зберегти':'Додати'}</button></div>`);document.getElementById('svc-save').onclick=async()=>{const category=document.getElementById('svc-category').value,title=document.getElementById('svc-title').value.trim(),price=num(document.getElementById('svc-price').value),description=document.getElementById('svc-desc').value.trim();if(!title){alert('Вкажіть назву породи або послуги.');return}try{if(isEdit){await api('/services/'+encodeURIComponent(item.id),{method:'PATCH',body:JSON.stringify({title,price:String(price),description,category})})}else{await api('/services',{method:'POST',body:JSON.stringify({title,price:String(price),duration:'',category,description,image:'',active:true,order:999})})}closeModal();render(category)}catch(e){alert('Не вдалося зберегти: '+e.message)}}}
async function remove(item){if(!item?.id||!confirm(`Видалити «${item.title}»?`))return;try{await api('/services/'+encodeURIComponent(item.id),{method:'PATCH',body:JSON.stringify({active:false})});render(categoryOf(item))}catch(e){alert('Не вдалося видалити: '+e.message)}}
async function render(selected){styles();const root=document.getElementById('view-services');if(!root)return;document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));root.classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view==='services'));document.getElementById('page-title').textContent='Послуги';let items=[];try{const d=await api('/services');items=(Array.isArray(d)?d:[]).filter(x=>x.active!==false)}catch(e){root.innerHTML=`<div class="card error">Помилка: ${esc(e.message)}</div>`;return}const active=KEYS.includes(selected)?selected:(items.length?categoryOf(items[0]):'complex');const counts=Object.fromEntries(KEYS.map(k=>[k,items.filter(x=>categoryOf(x)===k).length]));root.innerHTML=`<div class="svc-head"><div><h3>Послуги</h3><p>Керуйте чотирма розділами. У кожному можна додати породу або назву послуги та її ціну.</p></div><button class="small-btn gold" id="svc-new">＋ Додати</button></div><div class="cat-tabs">${KEYS.map(k=>`<button class="cat-tab ${k===active?'active':''}" data-cat="${k}">${CATEGORIES[k]} <span>(${counts[k]})</span></button>`).join('')}</div><div class="svc-list" id="svc-list"></div>`;root.querySelector('#svc-new').onclick=()=>openEditor({category:active});root.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>render(b.dataset.cat));const list=root.querySelector('#svc-list'),group=items.filter(x=>categoryOf(x)===active);if(!group.length){list.innerHTML=`<div class="cat-empty">У розділі «${CATEGORIES[active]}» поки немає позицій. Натисніть «＋ Додати».</div>`;return}list.innerHTML=group.map(x=>`<article class="svc-card"><div class="svc-top"><div><div class="svc-name">${esc(x.title)}</div><div class="svc-cat">${CATEGORIES[active]}</div>${x.description?`<div class="svc-desc">${esc(x.description)}</div>`:''}</div><div class="svc-price">${num(x.price).toLocaleString('uk-UA')} грн</div></div><div class="svc-actions"><button class="small-btn gold" data-edit="${esc(x.id)}">Редагувати</button><button class="small-btn svc-delete" data-delete="${esc(x.id)}">Видалити</button></div></article>`).join('');list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(group.find(x=>String(x.id)===String(b.dataset.edit))));list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(group.find(x=>String(x.id)===String(b.dataset.delete))))}
function intercept(e){const b=e.target.closest?.('[data-view="services"]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();render()}document.addEventListener('click',intercept,true);window.royalPetRenderServices=render;
})();
