(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const clean=v=>String(v??'').trim().replace(/\s*грн\.?\s*$/i,'').trim();
const rangeText=v=>{const raw=clean(v);if(!raw)return'Ціна уточнюється';const m=raw.match(/^(\d+(?:[.,]\d+)?)\s*[–—-]\s*(\d+(?:[.,]\d+)?)$/);if(!m)return`${raw} грн`;const a=Number(m[1].replace(',','.')),b=Number(m[2].replace(',','.'));return a===b?`${a.toLocaleString('uk-UA')} грн`:`${a.toLocaleString('uk-UA')}–${b.toLocaleString('uk-UA')} грн`};
let listTimer=0;
async function enhanceList(){clearTimeout(listTimer);listTimer=setTimeout(async()=>{const root=document.getElementById('view-services');if(!root)return;const cards=[...root.querySelectorAll('.svc-card')].filter(c=>c.querySelector('.svc-name'));if(!cards.length)return;try{const r=await fetch(API+'/services',{credentials:'include',cache:'no-store'});if(!r.ok)return;const data=await r.json();const byTitle=new Map((Array.isArray(data)?data:[]).map(x=>[String(x.title||''),x]));cards.forEach(card=>{const title=card.querySelector('.svc-name')?.textContent?.trim();const price=card.querySelector('.svc-price');const item=byTitle.get(title);if(!price||!item)return;const text=rangeText(item.price);if(price.textContent!==text)price.textContent=text;});}catch{}},80)}
function enhanceModal(){const price=document.getElementById('s-price');if(!price||price.dataset.rangeReady==='1')return;const wrap=price.closest('label');if(!wrap)return;price.dataset.rangeReady='1';const current=clean(price.value);let from='',to='';const m=current.match(/^(\d+(?:[.,]\d+)?)\s*[–—-]\s*(\d+(?:[.,]\d+)?)$/);if(m){from=m[1].replace(',','.');to=m[2].replace(',','.')}else if(current)from=current.replace(',','.');price.style.display='none';const box=document.createElement('div');box.className='rp-price-range';box.innerHTML='<div><input id="rp-price-from" type="number" min="0" step="1" placeholder="Від"><b>—</b><input id="rp-price-to" type="number" min="0" step="1" placeholder="До"></div><small>Для фіксованої ціни заповніть тільки «Від».</small>';wrap.appendChild(box);document.getElementById('rp-price-from').value=from;document.getElementById('rp-price-to').value=to;const save=document.getElementById('svc-save');if(save&&!save.dataset.rangeHooked){save.dataset.rangeHooked='1';const original=save.onclick;save.onclick=async e=>{const a=document.getElementById('rp-price-from')?.value.trim()||'';const b=document.getElementById('rp-price-to')?.value.trim()||'';if(a&&b&&Number(b)<Number(a)){alert('Ціна «До» не може бути меншою за «Від».');return}price.value=a&&b?`${a}–${b}`:a||b||'';if(original)return original.call(save,e)}}}
function css(){if(document.getElementById('rp-services-range-css'))return;const s=document.createElement('style');s.id='rp-services-range-css';s.textContent='.rp-price-range{margin-top:7px}.rp-price-range>div{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:8px}.rp-price-range input{margin-top:0!important}.rp-price-range b{color:#777;text-align:center}.rp-price-range small{display:block;margin-top:6px;color:#777;font-size:11px;line-height:1.35}@media(max-width:520px){.rp-price-range>div{grid-template-columns:1fr}.rp-price-range b{display:none}.rp-price-range input{min-height:44px}.svc-price{white-space:normal!important}}';document.head.appendChild(s)}
function init(){css();const observer=new MutationObserver(()=>{enhanceModal();enhanceList()});observer.observe(document.body,{childList:true,subtree:true});enhanceModal();enhanceList()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
