(()=>{
'use strict';
const API='https://royal-pet-admin-api.dolanhash1.workers.dev';
const CONFIG_KEY='__booking_config__';
const form=document.getElementById('booking-form');
const servicesRoot=document.getElementById('services');
const breedSelect=document.getElementById('breed');
const dateInput=document.getElementById('booking-date');
const timeSelect=document.getElementById('booking-time');
const availabilityMessage=document.getElementById('availability-message');
const formMessage=document.getElementById('form-message');
const submitButton=document.getElementById('submit-button');
const days=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];
const DOG_BREEDS=['Йоркширський тер’єр','Померанський шпіц','Шпіц німецький','Мальтіпу','Мальтезе','Той-пудель','Чихуахуа','Той-тер’єр','Пекінес','Ши-тцу','Французький бульдог','Мопс','Джек-рассел-тер’єр','Кавалер-кінг-чарльз-спанієль','Кокер-спанієль','Бігль','Шарпей','Бордер-колі','Австралійська вівчарка','Самоїд','Середній пудель','Басенджі','Лабрадор-ретривер','Золотистий ретривер','Німецька вівчарка','Хаскі','Маламут','Доберман','Ротвейлер','Боксер','Далматинець','Великий пудель','Бернський зенненхунд','Ньюфаундленд','Алабай','Інша порода'];
const CAT_BREEDS=['Британська короткошерста','Шотландська висловуха','Мейн-кун','Сибірська','Перська','Бенгальська','Сфінкс','Регдол','Абіссінська','Бірманська','Норвезька лісова','Орієнтальна','Дворова / метис','Інша порода'];
const DOG_SERVICES=['Комплекс','Гігієна','Адаптація','Вичісування линяючої шерсті шпіца + купання','Вичісування линяючої шерсті шпіца','Вичісування ковтунів','Збривання ковтунів','Купання до 10 кг','Гігієна зубів','Гігієна очей'];
const CAT_SERVICES=['Комплексний грумінг кота','Гігієнічний грумінг кота','Купання та сушка кота','Вичісування кота','Вичісування ковтунів у кота','Підстригання кігтів','Гігієна очей та вух'];
let config={breeds:{dog:[...DOG_BREEDS],cat:[...CAT_BREEDS]},services:[],dogServices:[],catServices:[]},appointments=[],hours={};
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const text=v=>String(v??'').trim().toLowerCase();
const setMessage=(el,v,type='')=>{el.className=type?`message ${type}`:'message';el.textContent=v||''};
async function api(path,options={}){const r=await fetch(API+path,{credentials:'include',cache:'no-store',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`API ${r.status}`);return d}
async function publicApi(path){const r=await fetch(API+path,{credentials:'omit',cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(`PUBLIC API ${r.status}`);return d}
function normalizeService(s,i,animal='all'){if(typeof s==='string')return{id:`service-${i+1}`,title:s.trim(),animal};return{id:String(s?.id||`service-${i+1}`),title:String(s?.title||s?.name||'').trim(),category:s?.category,animal:s?.animal??animal,pet_type:s?.pet_type,animal_type:s?.animal_type,animal_type_label:s?.animal_type_label,petType:s?.petType,type:s?.type,active:s?.active!==false}}
function animalOfService(s){const v=[s?.category,s?.animal,s?.pet_type,s?.animal_type,s?.animal_type_label,s?.petType,s?.type].map(text).filter(Boolean).join(' | ');if(/cat|feline|кіт|коти|котик|котики|коты/.test(v))return'cat';if(/dog|canine|собак|пес/.test(v))return'dog';return'all'}
function applyConfig(saved){if(!saved||typeof saved!=='object')return;if(saved.breeds&&typeof saved.breeds==='object')for(const k of ['dog','cat'])if(Array.isArray(saved.breeds[k]))config.breeds[k]=saved.breeds[k].map(x=>Array.isArray(x)?String(x[0]??''):String(x??'')).filter(Boolean);if(Array.isArray(saved.dogServices))config.dogServices=saved.dogServices.map((s,i)=>normalizeService(s,i,'dog')).filter(s=>s.title&&s.active);if(Array.isArray(saved.catServices))config.catServices=saved.catServices.map((s,i)=>normalizeService(s,i,'cat')).filter(s=>s.title&&s.active);if(Array.isArray(saved.services))config.services=saved.services.map((s,i)=>normalizeService(s,i)).filter(s=>s.title&&s.active)}
async function loadConfig(){try{const d=await api('/hours?booking_config='+Date.now());applyConfig(typeof d?.[CONFIG_KEY]==='string'?JSON.parse(d[CONFIG_KEY]):d?.[CONFIG_KEY])}catch{}if(!config.dogServices.length)config.dogServices=DOG_SERVICES.map((x,i)=>normalizeService(x,i,'dog'));if(!config.catServices.length)config.catServices=CAT_SERVICES.map((x,i)=>normalizeService(x,i,'cat'))}
function renderServices(){const cat=form.querySelector('[name="pet_type"]:checked')?.value==='Кіт';let list=cat?config.catServices:config.dogServices;if(!list.length)list=config.services.filter(s=>animalOfService(s)==='all'||animalOfService(s)===(cat?'cat':'dog'));servicesRoot.innerHTML=list.length?list.map(s=>`<label class="service-option"><input type="checkbox" name="services" value="${esc(s.title)}"><span><b>${esc(s.title)}</b><small>${cat?'Royal Pet · догляд за котиком':'Royal Pet · догляд за улюбленцем'}</small></span><i>›</i></label>`).join(''):'<div class="loading-state">Послуг поки немає.</div>'}
function renderBreeds(){const cat=form.querySelector('[name="pet_type"]:checked')?.value==='Кіт';const list=config.breeds[cat?'cat':'dog']||[];breedSelect.innerHTML='<option value="">Оберіть породу</option>'+list.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function parseHours(v){const m=String(v||'').match(/(\d{1,2}:\d{2})\s*[–—-]\s*(\d{1,2}:\d{2})/);if(/вихідний|закрит/i.test(String(v||'')))return{closed:true,from:'09:00',to:'19:00'};return{closed:false,from:m?.[1]||'09:00',to:m?.[2]||'19:00'}}
const mins=v=>{const[a,b]=String(v).split(':').map(Number);return a*60+b};
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function setMinimumDate(){const now=new Date();dateInput.min=dateKey(now);if(!dateInput.value||dateInput.value<dateInput.min){const d=new Date(now);d.setDate(d.getDate()+1);dateInput.value=dateKey(d)}}
async function loadAvailability(){const key=dateInput.value;timeSelect.innerHTML='<option value="">Завантажуємо доступний час…</option>';setMessage(availabilityMessage,'');if(!key)return;try{const h=await publicApi('/public/hours?sync='+Date.now());hours=h||{};const raw=hours[`date:${key}`]??hours[days[new Date(key+'T12:00:00').getDay()]];const schedule=parseHours(raw);if(schedule.closed){timeSelect.innerHTML='<option value="">Цього дня вихідний</option>';setMessage(availabilityMessage,'У цей день Royal Pet не працює. Оберіть іншу дату.','error');return}let busy=new Set();try{const a=await publicApi('/public/availability?date='+encodeURIComponent(key)+'&sync='+Date.now());(Array.isArray(a?.slots)?a.slots:[]).filter(x=>x?.status==='busy').forEach(x=>busy.add(String(x.time).slice(0,5)))}catch{try{const a=await publicApi('/public/appointments?date='+encodeURIComponent(key));(Array.isArray(a)?a:a?.appointments||[]).forEach(x=>{const d=new Date(x.preferred_time);if(!Number.isNaN(d.getTime()))busy.add(`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`)})}catch{}}timeSelect.innerHTML='<option value="">Оберіть доступний час</option>';const now=new Date(),today=dateKey(now),current=now.getHours()*60+now.getMinutes();let count=0;for(let m=mins(schedule.from);m<mins(schedule.to);m+=30){if(key===today&&m<=current)continue;const t=`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;if(busy.has(t))continue;const o=document.createElement('option');o.value=t;o.textContent=t;timeSelect.appendChild(o);count++}setMessage(availabilityMessage,count?`Доступно годин для запису: ${count}.`:'На цю дату вільного часу немає. Оберіть іншу дату.',count?'success':'error')}catch(e){timeSelect.innerHTML='<option value="">Не вдалося завантажити доступний час</option>';setMessage(availabilityMessage,'Не вдалося завантажити графік.','error')}}
async function submitBooking(e){e.preventDefault();setMessage(formMessage,'');if(!form.reportValidity())return;const selected=[...form.querySelectorAll('[name="services"]:checked')].map(i=>i.value);if(!selected.length){setMessage(formMessage,'Будь ласка, оберіть хоча б одну послугу.','error');return}if(!timeSelect.value){setMessage(formMessage,'Будь ласка, оберіть доступний час.','error');return}const type=form.querySelector('[name="pet_type"]:checked')?.value||'Собака';const payload={pet_name:form.elements.pet_name.value.trim(),age:form.elements.pet_age.value.trim(),breed:form.elements.breed.value.trim(),owner_name:form.elements.owner_name.value.trim(),owner_contact:form.elements.phone.value.trim(),preferred_time:`${dateInput.value}T${timeSelect.value}`,additional_services:selected.join(', '),home_care:`Вид тварини: ${type}`,comment:form.elements.comment.value.trim()};submitButton.disabled=true;setMessage(formMessage,'Надсилаємо заявку…');try{await api('/appointments',{method:'POST',body:JSON.stringify(payload)});setMessage(formMessage,'Заявку успішно надіслано ✓ Вона вже з’явилася в кабінеті Royal Pet у розділі «Записи».','success');form.reset();form.querySelector('[name="pet_type"][value="Собака"]').checked=true;renderBreeds();renderServices();setMinimumDate();await loadAvailability()}catch(err){setMessage(formMessage,`Не вдалося надіслати заявку: ${err?.message||'помилка'}`,'error')}finally{submitButton.disabled=false}}
async function init(){setMinimumDate();await loadConfig();renderServices();renderBreeds();form.querySelectorAll('[name="pet_type"]').forEach(x=>x.addEventListener('change',()=>{renderBreeds();renderServices()}));dateInput.addEventListener('change',loadAvailability);form.addEventListener('submit',submitBooking);await loadAvailability()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
