(()=>{
'use strict';
const API='https://royal-pet-admin-api.dolanhash1.workers.dev';
const CONFIG_KEY='__booking_config__';
const form=document.getElementById('booking-form'),servicesRoot=document.getElementById('services'),breedSelect=document.getElementById('breed'),dateInput=document.getElementById('booking-date'),timeSelect=document.getElementById('booking-time'),availabilityMessage=document.getElementById('availability-message'),formMessage=document.getElementById('form-message'),submitButton=document.getElementById('submit-button');
let config={breeds:{dog:[],cat:[]},services:[],dogServices:[],catServices:[]};
let schedule={};
const DAY_KEYS=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const text=v=>String(v??'').trim().toLowerCase();
const setMessage=(el,v,type='')=>{el.className=type?`message ${type}`:'message';el.textContent=v||''};
async function publicApi(path,options={}){const r=await fetch(API+path,{credentials:'omit',cache:'no-store',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`PUBLIC API ${r.status}`);return d}
function normalizeService(s,i,animal='all'){if(typeof s==='string')return{id:`service-${i+1}`,title:s.trim(),animal};return{id:String(s?.id||`service-${i+1}`),title:String(s?.title||s?.name||'').trim(),animal:s?.animal??animal,category:s?.category,pet_type:s?.pet_type,animal_type:s?.animal_type,animal_type_label:s?.animal_type_label,petType:s?.petType,type:s?.type,active:s?.active!==false}}
function animalOfService(s){const v=[s?.animal,s?.category,s?.pet_type,s?.animal_type,s?.animal_type_label,s?.petType,s?.type].map(text).filter(Boolean).join(' | ');if(/cat|feline|кіт|коти|котик|котики|коты/.test(v))return'cat';if(/dog|canine|собак|пес/.test(v))return'dog';return'all'}
function applyConfig(saved){if(!saved||typeof saved!=='object')return;if(saved.breeds&&typeof saved.breeds==='object')for(const k of ['dog','cat'])if(Array.isArray(saved.breeds[k]))config.breeds[k]=saved.breeds[k].map(x=>Array.isArray(x)?String(x[0]??'').trim():String(x??'').trim()).filter(Boolean);if(Array.isArray(saved.dogServices))config.dogServices=saved.dogServices.map((s,i)=>normalizeService(s,i,'dog')).filter(s=>s.title&&s.active);if(Array.isArray(saved.catServices))config.catServices=saved.catServices.map((s,i)=>normalizeService(s,i,'cat')).filter(s=>s.title&&s.active);if(Array.isArray(saved.services))config.services=saved.services.map((s,i)=>normalizeService(s,i)).filter(s=>s.title&&s.active)}
async function loadConfig(){try{const d=await publicApi('/public/hours?booking_config='+Date.now());let raw=d?.[CONFIG_KEY];if(typeof raw==='string')raw=JSON.parse(raw);applyConfig(raw);schedule=d&&typeof d==='object'?d:schedule}catch(e){console.warn('[Royal Pet] booking config/schedule sync:',e)}}
function renderBreeds(){const cat=form.querySelector('[name="pet_type"]:checked')?.value==='Кіт',list=config.breeds[cat?'cat':'dog']||[];breedSelect.innerHTML='<option value="">Оберіть породу</option>'+list.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function renderServices(){const cat=form.querySelector('[name="pet_type"]:checked')?.value==='Кіт';let list=cat?config.catServices:config.dogServices;if(!list.length)list=config.services.filter(s=>animalOfService(s)==='all'||animalOfService(s)===(cat?'cat':'dog'));servicesRoot.innerHTML=list.length?list.map(s=>`<label class="service-option"><input type="checkbox" name="services" value="${esc(s.title)}"><span><b>${esc(s.title)}</b><small>Royal Pet · ${cat?'догляд за котиком':'догляд за улюбленцем'}</small></span><i>›</i></label>`).join(''):'<div class="loading-state">Послуг поки немає.</div>'}
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function setMinimumDate(){const now=new Date();dateInput.min=dateKey(now);if(!dateInput.value||dateInput.value<dateInput.min){const d=new Date(now);d.setDate(d.getDate()+1);dateInput.value=dateKey(d)}}
function exactScheduleSlots(value){return String(value||'').split(';').map(part=>{const m=part.trim().match(/^(\d{1,2}:\d{2})(?:\s*[–—-]\s*\d{1,2}:\d{2})?$/);if(!m)return null;const m2=m[1].match(/^(\d{1,2}):(\d{2})$/);if(!m2)return null;const hh=Number(m2[1]),mm=Number(m2[2]);if(hh>23||mm>59)return null;const t=`${String(hh).padStart(2,'0')}:${String(mm).padStart(2,'0')}`;return{time:t,label:t}}).filter(Boolean)}
function scheduleForDate(key,hours){const d=new Date(key+'T12:00:00'),day=DAY_KEYS[d.getDay()];return String(hours?.['date:'+key]??hours?.[day]??'')}
async function loadAvailability(){const key=dateInput.value;timeSelect.innerHTML='<option value="">Завантажуємо доступний час…</option>';setMessage(availabilityMessage,'');if(!key)return;try{const hours=await publicApi('/public/hours?schedule='+Date.now());let slots=[];try{const a=await publicApi('/public/availability?date='+encodeURIComponent(key)+'&sync='+Date.now());slots=Array.isArray(a?.slots)?a.slots:[]}catch(e){console.warn('[Royal Pet] availability endpoint:',e)}const exact=exactScheduleSlots(scheduleForDate(key,hours));const busy=new Set(slots.filter(x=>x&&x.status==='busy').map(x=>String(x.time).slice(0,5)));const free=exact.map(x=>x.time).filter(t=>!busy.has(t));timeSelect.innerHTML='<option value="">Оберіть доступний час</option>';free.forEach(t=>{const o=document.createElement('option');o.value=t;o.textContent=t;timeSelect.appendChild(o)});const isOpen=exact.length>0;if(isOpen&&free.length)setMessage(availabilityMessage,`Доступно годин: ${free.length}.`,'success');else setMessage(availabilityMessage,isOpen?'На цю дату вільних годин немає. Оберіть іншу дату.':'У цей день Royal Pet не працює. Оберіть іншу дату.','error')}catch(e){timeSelect.innerHTML='<option value="">Не вдалося завантажити доступний час</option>';setMessage(availabilityMessage,'Не вдалося завантажити графік.','error');console.error('[Royal Pet] availability:',e)}}
async function submitBooking(e){e.preventDefault();setMessage(formMessage,'');if(!form.reportValidity())return;const selected=[...form.querySelectorAll('[name="services"]:checked')].map(i=>i.value);if(!selected.length)return setMessage(formMessage,'Будь ласка, оберіть хоча б одну послугу.','error');if(!timeSelect.value)return setMessage(formMessage,'Будь ласка, оберіть доступний час.','error');const allowed=new Set(exactScheduleSlots(scheduleForDate(dateInput.value,schedule)).map(x=>x.time));if(!allowed.has(timeSelect.value))return setMessage(formMessage,'Обраний час не відповідає графіку роботи. Оберіть інший час.','error');const type=form.querySelector('[name="pet_type"]:checked')?.value||'Собака',payload={pet_name:form.elements.pet_name.value.trim(),age:form.elements.pet_age.value.trim(),breed:form.elements.breed.value.trim(),owner_name:form.elements.owner_name.value.trim(),owner_contact:form.elements.phone.value.trim(),preferred_time:`${dateInput.value}T${timeSelect.value}`,additional_services:selected.join(', '),home_care:`Вид тварини: ${type}`,comment:form.elements.comment.value.trim()};submitButton.disabled=true;setMessage(formMessage,'Надсилаємо заявку…');try{await publicApi('/appointments',{method:'POST',body:JSON.stringify(payload)});setMessage(formMessage,'Заявку успішно надіслано ✓ Вона вже з’явилася в кабінеті Royal Pet у розділі «Записи».','success');form.reset();form.querySelector('[name="pet_type"][value="Собака"]').checked=true;renderBreeds();renderServices();setMinimumDate();await loadAvailability()}catch(err){setMessage(formMessage,`Не вдалося надіслати заявку: ${err?.message||'помилка'}`,'error')}finally{submitButton.disabled=false}}
async function init(){setMinimumDate();await loadConfig();renderBreeds();renderServices();form.querySelectorAll('[name="pet_type"]').forEach(x=>x.addEventListener('change',()=>{renderBreeds();renderServices()}));dateInput.addEventListener('change',loadAvailability);form.addEventListener('submit',submitBooking);await loadAvailability()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();