(()=>{
'use strict';
if(!window.matchMedia('(max-width:620px)').matches)return;
const API='https://royal-pet-admin-api.dolanhash1.workers.dev';
const DOG_BREEDS=['Йоркширський тер’єр','Померанський шпіц','Шпіц німецький','Мальтіпу','Мальтезе','Той-пудель','Чихуахуа','Той-тер’єр','Пекінес','Ши-тцу','Французький бульдог','Мопс','Джек-рассел-тер’єр','Кавалер-кінг-чарльз-спанієль','Кокер-спанієль','Бігль','Шарпей','Бордер-колі','Австралійська вівчарка','Самоїд','Середній пудель','Басенджі','Лабрадор-ретривер','Золотистий ретривер','Німецька вівчарка','Хаскі','Маламут','Доберман','Ротвейлер','Боксер','Далматинець','Великий пудель','Бернський зенненхунд','Ньюфаундленд','Алабай','Інша порода'];
const CAT_BREEDS=['Британська короткошерста','Шотландська висловуха','Мейн-кун','Сибірська','Перська','Бенгальська','Сфінкс','Регдол','Абіссінська','Бірманська','Норвезька лісова','Орієнтальна','Дворова / метис','Інша порода'];
const DOG_SERVICES=['Комплекс','Гігієна','Адаптація','Вичісування линяючої шерсті шпіца + купання','Вичісування линяючої шерсті шпіца','Вичісування ковтунів','Збривання ковтунів','Купання до 10 кг','Гігієна зубів','Гігієна очей'];
const CAT_SERVICES=['Комплексний грумінг кота','Гігієнічний грумінг кота','Купання та сушка кота','Вичісування кота','Вичісування ковтунів у кота','Підстригання кігтів','Гігієна очей та вух'];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const form=()=>document.getElementById('booking-form');
function render(){const f=form();if(!f)return;const type=f.querySelector('[name="pet_type"]:checked')?.value==='Кіт'?'cat':'dog';const breed=f.querySelector('#breed');if(breed){const breeds=type==='cat'?CAT_BREEDS:DOG_BREEDS;breed.innerHTML='<option value="">Оберіть породу</option>'+breeds.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
const root=f.querySelector('#services');if(root){const services=type==='cat'?CAT_SERVICES:DOG_SERVICES;root.innerHTML=services.map(x=>`<label class="service-option"><input type="checkbox" name="services" value="${esc(x)}"><span><b>${esc(x)}</b><small>${type==='cat'?'Royal Pet · догляд за котиком':'Royal Pet · догляд за улюбленцем'}</small></span><i>›</i></label>`).join('')}}
async function time(){const f=form();if(!f)return;const date=f.querySelector('#booking-date'),sel=f.querySelector('#booking-time'),msg=f.querySelector('#availability-message');if(!date||!sel||!date.value)return;try{const r=await fetch(`${API}/public/hours?sync=${Date.now()}`,{cache:'no-store',credentials:'omit'});if(!r.ok)throw Error();const h=await r.json();const raw=String(h?.[`date:${date.value}`]||'').trim();const times=[...raw.matchAll(/(\d{1,2}:\d{2})\s*[–—-]\s*(\d{1,2}:\d{2})/g)];if(!times.length){sel.innerHTML='<option value="">На цю дату запис недоступний</option>';if(msg){msg.className='message error';msg.textContent='На цю дату графік не заданий.'}return}const start=times[0][1],end=times[0][2];const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);const busy=new Set();try{const br=await fetch(`${API}/public/availability?date=${encodeURIComponent(date.value)}&sync=${Date.now()}`,{cache:'no-store',credentials:'omit'});if(br.ok){const d=await br.json();(d?.slots||[]).filter(x=>x?.status==='busy').forEach(x=>busy.add(x.time))}}catch{}let out='<option value="">Оберіть доступний час</option>';for(let m=sh*60+sm;m<eh*60+em;m+=30){const t=`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;if(!busy.has(t))out+=`<option value="${t}">${t}</option>`}sel.innerHTML=out;if(msg){msg.className='message success';msg.textContent=`Доступно годин для запису: ${Math.max(0,(out.match(/<option/g)||[]).length-1)}.`}}catch{if(!sel.options.length||sel.options.length===1)sel.innerHTML='<option value="">Не вдалося завантажити доступний час</option>'}}
function init(){const f=form();if(!f)return;render();f.querySelectorAll('[name="pet_type"]').forEach(x=>x.addEventListener('change',render));f.querySelector('#booking-date')?.addEventListener('change',time);time()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
