(()=>{
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const DAY=['Неділя','Понеділок','Вівторок','Середа','Четвер','П’ятниця','Субота'];
const V='schedule-guard-20260912-v2';
const parse=v=>[...String(v||'').matchAll(/(\d{1,2}):(\d{2})\s*[–—-]\s*(\d{1,2}):(\d{2})/g)].map(m=>({open:+m[1]*60 + +m[2],close:+m[3]*60 + +m[4]})).filter(x=>x.open<x.close);
const fmt=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
const dateInput=()=>document.querySelector('.rp-time-field input[type="date"]');
async function hours(){const r=await fetch(API+'/public/hours?guard='+Date.now(),{cache:'no-store',credentials:'omit'});if(!r.ok)throw Error('hours_'+r.status);return r.json()}
function closed(box,date){box.innerHTML=`<div class="rp-closed" style="grid-column:1/-1">${DAY[new Date(date+'T12:00:00').getDay()]} — у цей день запис недоступний.</div>`}
async function check(){const d=dateInput(),slots=document.querySelector('.rp-slots');if(!d||!slots)return;const date=d.value;try{const h=await hours(),raw=h['date:'+date],intervals=parse(raw);if(!raw||raw==='__DEFAULT__'||/вихідний/i.test(raw)||!intervals.length){slots.innerHTML='';closed(slots,date);const p=document.querySelector('[name="preferred_time"]');if(p)p.value='';return}
const availability=await fetch(API+'/public/availability?date='+encodeURIComponent(date)+'&guard='+Date.now(),{cache:'no-store',credentials:'omit'});const data=availability.ok?await availability.json():null;const apiSlots=Array.isArray(data?.slots)&&data.open?data.slots:[];const status=new Map(apiSlots.map(x=>[x.time,x.status]));const times=intervals.map(x=>fmt(x.open));slots.innerHTML='';times.forEach(time=>{const busy=status.get(time)==='busy',b=document.createElement('button');b.type='button';b.className='rp-slot '+(busy?'busy':'free');b.disabled=busy;b.innerHTML=`<span class="rp-slot-time">${time}</span><span class="rp-slot-status">${busy?'Зайнято':'Вільно'}</span>`;b.onclick=()=>{slots.querySelectorAll('.rp-slot.selected').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const p=document.querySelector('[name="preferred_time"]');if(p)p.value=date+'T'+time;const s=document.querySelector('.rp-selected-time');if(s)s.textContent='Обрано: '+date.split('-').reverse().join('.')+' о '+time};slots.appendChild(b)})
}catch(e){console.error('Schedule guard',e)}}
async function init(){if(document.documentElement.dataset.scheduleGuard===V)return;document.documentElement.dataset.scheduleGuard=V;const d=dateInput();if(!d){setTimeout(init,150);return}d.addEventListener('change',check);setTimeout(check,200);const f=document.getElementById('booking-form');if(f)f.addEventListener('submit',async e=>{const p=f.querySelector('[name="preferred_time"]');if(!p?.value)return;try{const h=await hours(),date=p.value.slice(0,10),raw=h['date:'+date];if(!raw||raw==='__DEFAULT__'||/вихідний/i.test(raw)||!parse(raw).length){e.preventDefault();e.stopImmediatePropagation();const m=document.getElementById('form-message');if(m)m.textContent='❌ На обрану дату графік не заданий.';return}}catch{e.preventDefault();e.stopImmediatePropagation()}},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();