(()=>{
'use strict';
const API=(window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const CATEGORIES={complex:{title:'Комплекс',text:'Повний комплекс догляду з урахуванням породи та стану шерсті.'},hygiene:{title:'Гігієна',text:'Гігієнічні процедури для чистоти, комфорту та здоров’я улюбленця.'},adaptive:{title:'Адаптаційний грумінг',text:'Дбайливий формат для улюбленців, яким потрібен адаптаційний підхід.'},additional:{title:'Додаткові послуги',text:'Окремі процедури та доповнення до основного грумінгу.'}};
const KEYS=Object.keys(CATEGORIES);
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const img=v=>v&&String(v).startsWith('/uploads/')?'.'+v:String(v||'');
const animal=x=>{const c=String(x?.category||'').trim().toLowerCase();return ['cat','cats','кіт','коти','котики','коты','коти/котики'].includes(c)?'cat':'dog'};
function normalizeCategory(x){const c=String(x?.category||'').trim().toLowerCase();if(c==='complex'||c==='комплекс'||c==='грумінг'||c==='грумінг / комплекс'||c==='комплексний грумінг'||c==='грумінг (комплекс)'||c==='комплексний грумінг / догляд')return'complex';if(c==='hygiene'||c==='гігієна'||c==='гігієнічний грумінг')return'hygiene';if(c==='adaptive'||c==='адаптивний грумінг'||c==='адаптаційний грумінг')return'adaptive';if(c==='additional'||c==='додаткові послуги')return'additional';if(x?.id==='service-1')return'complex';if(x?.id==='service-2'||x?.id==='service-3'||x?.id==='service-5')return'hygiene';if(x?.id==='service-4')return'adaptive';return'complex'}
async function getServices(){if(API){try{const r=await fetch(`${API}/public/services?sync=${Date.now()}`,{cache:'no-store'});if(r.ok){const d=await r.json();if(Array.isArray(d))return d.filter(x=>x.active!==false)}}catch{}}try{const path=location.pathname.includes('/services/')?'../../content/services.json':'content/services.json';const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});const d=await r.json();return Array.isArray(d.items)?d.items.filter(x=>x.active!==false):[]}catch{return[]}}
function price(v){const raw=String(v??'').trim().replace(/\s*грн\.?\s*$/i,'').trim();if(!raw)return'Ціна уточнюється';const m=raw.match(/^(\d+(?:[.,]\d+)?)\s*[–—-]\s*(\d+(?:[.,]\d+)?)$/);if(!m)return`${esc(raw)} грн`;const a=Number(m[1].replace(',','.')),b=Number(m[2].replace(',','.'));if(!Number.isFinite(a)||!Number.isFinite(b))return'Ціна уточнюється';return a===b?`${a.toLocaleString('uk-UA')} грн`:`${a.toLocaleString('uk-UA')}–${b.toLocaleString('uk-UA')} грн`}
function serviceCard(x){return `<article class="service-card"><div class="service-card-content">${x.image?`<div class="service-card-image"><img src="${esc(img(x.image))}" alt="${esc(x.title||'Royal Pet')}" loading="lazy"></div>`:''}<div class="service-card-top"><h3>${esc(x.title||'Без назви')}</h3><strong>${price(x.price)}</strong></div>${x.description?`<p>${esc(x.description)}</p>`:''}${x.duration?`<div class="service-card-meta"><span>⏱ ${esc(x.duration)}</span></div>`:''}</div></article>`}
function dogCatSection(title,emoji,items){return `<section class="animal-services-block"><h3 class="animal-services-title"><span>${emoji}</span> ${title}</h3><div class="animal-services-grid">${items.length?items.sort((a,b)=>(Number(a.order)||0)-(Number(b.order)||0)).map(serviceCard).join(''):'<div class="animal-services-empty">Послуг поки немає.</div>'}</div></section>`}
async function home(){const root=document.querySelector('[data-services]');if(!root)return;const items=await getServices();const dogs=items.filter(x=>animal(x)==='dog');const cats=items.filter(x=>animal(x)==='cat');root.className='service-grid animal-services';root.dataset.serviceCategoriesRendered='1';root.innerHTML=`${dogCatSection('Послуги для песиків','🐶',dogs)}${dogCatSection('Послуги для котиків','🐱',cats)}`;}
async function page(){const root=document.querySelector('[data-service-category-page]');if(!root)return;const key=String(root.dataset.serviceCategoryPage||'').trim();if(!KEYS.includes(key))return;const cat=CATEGORIES[key];root.innerHTML=`<section class="service-category-hero"><p class="eyebrow">Послуги</p><h1>${esc(cat.title)}</h1><p>${esc(cat.text)}</p><a class="text-link" href="../../#services">← Повернутися до послуг</a></section><section class="service-category-list-section"><div class="service-category-list" data-category-list><div class="service-loading">Завантаження…</div></div></section>`;const items=(await getServices()).filter(x=>normalizeCategory(x)===key);const list=root.querySelector('[data-category-list]');if(!items.length){list.innerHTML='<div class="service-empty">У цій категорії поки немає доданих позицій.</div>';return}list.innerHTML=items.sort((a,b)=>(Number(a.order)||0)-(Number(b.order)||0)).map(x=>`<article class="breed-price-card">${x.image?`<div class="breed-price-image"><img src="${esc(img(x.image))}" alt="${esc(x.title)}" loading="lazy"></div>`:''}<div class="breed-price-body"><h2>${esc(x.title||'Без назви')}</h2>${x.description?`<p>${esc(x.description)}</p>`:''}<strong>${price(x.price)}</strong></div></article>`).join('')}
function css(){if(document.getElementById('rp-animal-services-style'))return;const s=document.createElement('style');s.id='rp-animal-services-style';s.textContent=`.animal-services{display:grid!important;gap:34px}.animal-services-block{display:grid;gap:18px}.animal-services-title{margin:0;font-size:1.45rem;line-height:1.2}.animal-services-title span{font-size:1.1em}.animal-services-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.animal-services-empty{padding:20px;border:1px solid rgba(215,173,85,.18);border-radius:14px;color:#777;background:rgba(255,255,255,.02)}.animal-services .service-card{height:100%}@media(max-width:900px){.animal-services-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.animal-services{gap:28px}.animal-services-block{gap:14px}.animal-services-title{font-size:1.2rem}.animal-services-grid{grid-template-columns:1fr}.animal-services .service-card{width:100%}}`;document.head.appendChild(s)}
function watchHome(){const root=document.querySelector('[data-services]');if(!root||root.dataset.serviceCategoriesWatch)return;root.dataset.serviceCategoriesWatch='1';const obs=new MutationObserver(()=>{if(!root.dataset.serviceCategoriesLock&&(!root.querySelector('.animal-services-block')||root.querySelectorAll('.animal-services-block').length!==2))home()});obs.observe(root,{childList:true});setTimeout(home,350)}
function run(){css();page();watchHome();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();