(()=>{
const API=(window.ROYAL_PET_CUSTOMER_API||window.ROYAL_PET_ADMIN_API||'').replace(/\/$/,'');
const KEY='royal_pet_customer_session';
const STORE='royal_pet_customer';
const $=id=>document.getElementById(id);
function saveToken(value){if(value)localStorage.setItem(KEY,value);else localStorage.removeItem(KEY)}
function token(){return localStorage.getItem(KEY)||''}
function readStore(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
function writeStore(data){localStorage.setItem(STORE,JSON.stringify(data))}
function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
async function req(path,opt={}){const headers={Accept:'application/json',...(opt.headers||{})};if(token())headers.Authorization=`Bearer ${token()}`;const r=await fetch(`${API}${path}`,{...opt,headers,credentials:'omit',cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error([d.error,d.details&&`[${d.details}]`].filter(Boolean).join(' ')||`Помилка сервера (${r.status})`);return d}
function statusText(status){const s=String(status||'new').toLowerCase();return ({new:'Нова заявка',pending:'На підтвердженні',confirmed:'Підтверджено',scheduled:'Підтверджено',done:'Виконано',completed:'Виконано',cancelled:'Скасовано',canceled:'Скасовано',rejected:'Відхилено'})[s]||status||'Нова заявка'}
function statusClass(status){const s=String(status||'').toLowerCase();if(s.includes('cancel')||s.includes('reject'))return 'status-bad';if(s.includes('done')||s.includes('complete'))return 'status-done';if(s.includes('confirm')||s.includes('scheduled'))return 'status-good';return 'status-new'}
function normalizeAppointments(items){return (Array.isArray(items)?items:[]).map(x=>({...x,status_label:statusText(x.status)}))}
window.customerAuth={
 async me(){try{return (await req('/customer/me')).user||null}catch{return null}},
 async login(phone,password){const d=await req('/customer/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,password})});saveToken(d.token);return d.user},
 async register(name,phone,password){const d=await req('/customer/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,phone,password})});saveToken(d.token);return d.user},
 async logout(){try{await req('/customer/logout',{method:'POST'})}finally{saveToken('')}},
 async appointments(){return (await req('/customer/appointments')).appointments||[]},
 async cancelAppointment(id){return await req(`/customer/appointments/${encodeURIComponent(id)}/cancel`,{method:'POST'})},
 async updateProfile(name,phone){const d=await req('/customer/me',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,phone})});return d.user||null}
};
window.renderCustomerAuth=async()=>{const user=await window.customerAuth.me();const box=$('auth-area');if(!box)return;if(user){box.innerHTML=`<div class="auth-user"><div><strong>${esc(user.name)}</strong><span>${esc(user.phone)}</span></div><button class="ghost" id="logout">Вийти</button></div>`;$('logout').onclick=async()=>{$('logout').disabled=true;try{await window.customerAuth.logout()}finally{window.renderCustomerAuth();window.renderCustomerAppointments?.();window.renderCustomerProfile?.()}};return}
box.innerHTML=`<div class="auth-tabs"><button class="auth-tab active" data-mode="login">Вхід</button><button class="auth-tab" data-mode="register">Реєстрація</button></div><form id="auth-form"><div id="auth-name-wrap" class="hidden"><label>Ваше ім'я<input id="auth-name" autocomplete="name"></label></div><label>Телефон<input id="auth-phone" type="tel" autocomplete="tel" placeholder="+380..."></label><label>Пароль<input id="auth-password" type="password" minlength="6" autocomplete="current-password" placeholder="Мінімум 6 символів"></label><button class="primary" type="submit" id="auth-submit">Увійти</button><p class="message" id="auth-message"></p></form>`;
let mode='login';const tabs=box.querySelectorAll('.auth-tab');const apply=()=>{tabs.forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));$('auth-name-wrap').classList.toggle('hidden',mode!=='register');$('auth-password').autocomplete=mode==='register'?'new-password':'current-password';$('auth-submit').textContent=mode==='login'?'Увійти':'Створити акаунт'};tabs.forEach(x=>x.onclick=()=>{mode=x.dataset.mode;apply()});
$('auth-form').onsubmit=async e=>{e.preventDefault();const msg=$('auth-message');msg.textContent='Перевіряємо дані…';try{if(mode==='login')await window.customerAuth.login($('auth-phone').value.trim(),$('auth-password').value);else await window.customerAuth.register($('auth-name').value.trim(),$('auth-phone').value.trim(),$('auth-password').value);msg.textContent='✅ Готово';await window.renderCustomerAuth();await window.refreshCustomerAppointments?.();window.renderCustomerProfile?.()}catch(err){msg.textContent='❌ '+err.message}};apply()};
window.renderCustomerAppointments=async()=>{const root=$('appointments-list');if(!root)return;const user=await window.customerAuth.me();if(!user){root.innerHTML='<div class="empty-state"><h3>Увійдіть в акаунт</h3><p>Після входу тут будуть ваші записи та їхні статуси.</p></div>';return}root.innerHTML='<div class="empty-state">Завантажуємо ваші записи…</div>';try{const items=normalizeAppointments(await window.customerAuth.appointments());const data=readStore();data.appointments=items;data.profile={...(data.profile||{}),name:user.name,phone:user.phone};writeStore(data);if(!items.length){root.innerHTML='<div class="empty-state"><div class="empty-icon">✂</div><h3>Записів ще немає</h3><p>Оберіть послугу та зручний час — ваш перший запис зʼявиться тут.</p><button class="primary" id="empty-booking">Записатися</button></div>';$('empty-booking')?.addEventListener('click',()=>{location.hash='booking';window.dispatchEvent(new HashChangeEvent('hashchange'))});return}
root.innerHTML=`<div class="profile-summary"><strong>${esc(user.name)}</strong><span>${esc(user.phone)}</span><small>${items.length} ${items.length===1?'запис':'записів'}</small></div><div class="history-title">Історія записів</div>`+items.map(x=>{const d=esc(String(x.preferred_time||'').replace('T',' · '));const s=String(x.status||'new').toLowerCase();const canCancel=!['cancelled','canceled','done','completed','rejected'].includes(s);const canRepeat=['cancelled','canceled','done','completed','rejected'].includes(s);return `<article class="appointment-item"><div class="appointment-top"><strong>${esc(x.pet_name||'Улюбленець')}</strong><span class="${statusClass(x.status)}">${esc(x.status_label)}</span></div><div>${x.animal_type==='dog'?'🐶':'🐱'} ${esc(x.breed||'Порода не вказана')}</div><div class="appointment-time">📅 ${d||'Дата не вказана'}</div><div class="appointment-services">${esc(x.additional_services||x.services||'Послуги не вказані')}</div><div class="appointment-actions">${canRepeat?`<button type="button" class="ghost rebook-btn" data-id="${esc(x.id)}">Повторити запис</button>`:''}${canCancel?`<button type="button" class="danger-button cancel-btn" data-id="${esc(x.id)}">Скасувати запис</button>`:''}</div></article>`}).join('');
root.querySelectorAll('.cancel-btn').forEach(btn=>{btn.addEventListener('click',async()=>{const id=btn.dataset.id;if(!id)return;const item=items.find(x=>String(x.id)===String(id));const pet=item?.pet_name||'цей запис';if(!confirm(`Скасувати запис для «${pet}»?`))return;btn.disabled=true;btn.textContent='Скасовуємо…';try{await window.customerAuth.cancelAppointment(id);await window.renderCustomerAppointments();window.renderCustomerProfile?.()}catch(err){btn.disabled=false;btn.textContent='Скасувати запис';alert(err.message||'Не вдалося скасувати запис.')}})});
root.querySelectorAll('.rebook-btn').forEach(btn=>{btn.addEventListener('click',()=>{const item=items.find(x=>String(x.id)===String(btn.dataset.id));if(!item)return;localStorage.setItem('royal_pet_rebook_draft',JSON.stringify({pet_name:item.pet_name||'',animal_type:item.animal_type||'',breed:item.breed||'',age:item.age||'',additional_services:item.additional_services||item.services||''}));location.hash='booking';window.dispatchEvent(new HashChangeEvent('hashchange'));setTimeout(()=>window.applyRebookDraft?.(),100)})})
}catch(err){root.innerHTML=`<p class="message">❌ ${esc(err.message)}</p>`}};
window.refreshCustomerAppointments=async()=>{const user=await window.customerAuth.me();if(!user)return;await window.renderCustomerAppointments?.();window.renderCustomerProfile?.()};
window.renderCustomerProfile=async()=>{const note=$('profile-auth-note'),form=$('profile-form'),petsRoot=$('profile-pets');if(!note||!form||!petsRoot)return;const user=await window.customerAuth.me();if(!user){note.textContent='Увійдіть в акаунт, щоб бачити свої записи та улюбленців на будь-якому пристрої.';form.classList.add('hidden');petsRoot.innerHTML='';return}note.innerHTML=`Ви увійшли як <strong>${esc(user.name)}</strong>.`;form.classList.remove('hidden');$('profile-name').value=user.name||'';$('profile-phone').value=user.phone||'';try{const items=normalizeAppointments(await window.customerAuth.appointments());const pets=[];for(const x of items){if(x.pet_name&&!pets.some(p=>p.pet_name===x.pet_name))pets.push(x)}petsRoot.innerHTML=`<h3>Мої улюбленці</h3>`+(pets.length?pets.map(x=>`<div class="pet-mini"><span class="pet-icon">${x.animal_type==='dog'?'🐶':'🐱'}</span><b>${esc(x.pet_name)}</b><span>${esc(x.breed||'Порода не вказана')} · ${esc(x.age||'Вік не вказаний')}</span></div>`).join(''):'<p class="muted">Улюбленців ще немає. Додайте першого під час запису.</p>')}catch{petsRoot.innerHTML='<h3>Мої улюбленці</h3><p class="muted">Не вдалося завантажити список улюбленців.</p>'}};
window.bindCustomerProfileForm=()=>{const f=$('profile-form');if(!f||f.dataset.bound)return;f.dataset.bound='1';f.addEventListener('submit',async e=>{e.preventDefault();const msg=$('profile-message');const button=f.querySelector('button[type="submit"]');const name=$('profile-name').value.trim();const phone=$('profile-phone').value.trim();if(name.length<2){msg.textContent="❌ Вкажіть ім'я";return}if(phone.replace(/\D/g,'').length<8){msg.textContent='❌ Вкажіть правильний номер телефону';return}if(button)button.disabled=true;msg.textContent='Зберігаємо…';try{const user=await window.customerAuth.updateProfile(name,phone);const data=readStore();data.profile={...(data.profile||{}),name:user?.name||name,phone:user?.phone||phone};writeStore(data);await window.renderCustomerAuth?.();await window.renderCustomerAppointments?.();msg.textContent='✅ Профіль збережено';}catch(err){msg.textContent='❌ '+err.message}finally{if(button)button.disabled=false}setTimeout(()=>{if(msg.textContent.includes('збережено'))msg.textContent=''},2200)})};
window.applyRebookDraft=()=>{const raw=localStorage.getItem('royal_pet_rebook_draft');if(!raw)return false;let draft;try{draft=JSON.parse(raw)}catch{localStorage.removeItem('royal_pet_rebook_draft');return false}if(!$('booking')||$('booking').classList.contains('hidden'))return false;if($('animal')&&draft.animal_type){$('animal').value=draft.animal_type;$('animal').dispatchEvent(new Event('change'))}if($('pet'))$('pet').value=draft.pet_name||'';if($('age'))$('age').value=draft.age||'';if($('breed')&&draft.breed)$('breed').value=draft.breed;const names=String(draft.additional_services||'').split(',').map(x=>x.trim()).filter(Boolean);document.querySelectorAll('.service').forEach(card=>{const selected=names.includes(String(card.dataset.name||''));card.classList.toggle('selected',selected);const input=card.querySelector('input');if(input)input.checked=selected});const data=readStore(),profile=data.profile||{};if($('owner')&&!$('owner').value)$('owner').value=profile.name||'';if($('phone')&&!$('phone').value)$('phone').value=profile.phone||'';localStorage.removeItem('royal_pet_rebook_draft');return true};
window.bindCustomerProfileForm();window.renderCustomerAuth?.();
})();