(()=>{
const STORE='royal_pet_customer';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}};
const write=d=>localStorage.setItem(STORE,JSON.stringify(d));
function merge(items){const d=read(),pets=Array.isArray(d.pets)?d.pets:[];for(const x of Array.isArray(items)?items:[]){const n=String(x?.pet_name||'').trim();if(!n)continue;const i=pets.findIndex(p=>String(p.pet_name||'').trim().toLowerCase()===n.toLowerCase());const p={pet_name:n,animal_type:x.animal_type||'dog',breed:x.breed||'',age:x.age||''};if(i<0)pets.push(p);else pets[i]={...pets[i],...p}}d.pets=pets;write(d);return pets}
function makeDraft(p){return{pet_name:p.pet_name||'',animal_type:p.animal_type||'dog',breed:p.breed||'',age:p.age||'',additional_services:p.additional_services||''}}
function fillBooking(p){if(!p)return;const animal=document.getElementById('animal'),pet=document.getElementById('pet'),breed=document.getElementById('breed'),age=document.getElementById('age');if(animal){animal.value=p.animal_type||'dog';animal.dispatchEvent(new Event('change',{bubbles:true}))}if(pet)pet.value=p.pet_name||'';if(breed&&p.breed)breed.value=p.breed;if(age)age.value=p.age||'';localStorage.setItem('royal_pet_active_pet',JSON.stringify(makeDraft(p)))}
function book(p){localStorage.setItem('royal_pet_rebook_draft',JSON.stringify(makeDraft(p)));location.hash='booking';window.dispatchEvent(new HashChangeEvent('hashchange'));setTimeout(()=>window.applyRebookDraft?.(),120)}
function renderPicker(pets){const step=document.querySelector('#booking .step[data-step="1"]');if(!step)return;let box=step.querySelector('.pet-picker');if(!box){const h2=step.querySelector('h2');box=document.createElement('div');box.className='pet-picker';h2?.insertAdjacentElement('afterend',box)}const list=Array.isArray(pets)?pets:[];box.innerHTML=`<div class="pet-picker-head"><div><strong>Швидкий вибір</strong><span>Оберіть збереженого улюбленця</span></div>${list.length?'<button type="button" class="pet-picker-reset ghost">+ Новий</button>':''}</div>`+(list.length?`<div class="pet-picker-list">${list.map((p,i)=>`<button type="button" class="pet-choice" data-index="${i}"><span class="pet-choice-icon">${p.animal_type==='cat'?'🐱':'🐶'}</span><span class="pet-choice-text"><b>${esc(p.pet_name)}</b><small>${esc(p.breed||'Порода не вказана')} · ${esc(p.age||'Вік не вказаний')}</small></span></button>`).join('')}</div>`:'<p class="pet-picker-empty">Тут з’являться ваші збережені улюбленці.</p>');box.querySelector('.pet-picker-reset')?.addEventListener('click',()=>{document.getElementById('animal').value='';document.getElementById('pet').value='';document.getElementById('breed').innerHTML='<option value="">Спочатку оберіть тварину</option>';document.getElementById('age').value='';box.querySelectorAll('.pet-choice').forEach(x=>x.classList.remove('selected'));localStorage.removeItem('royal_pet_active_pet')});box.querySelectorAll('.pet-choice').forEach(btn=>btn.addEventListener('click',()=>{const p=list[+btn.dataset.index];if(!p)return;box.querySelectorAll('.pet-choice').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');fillBooking(p)}))}
function editor(root,pet,index,render){root.querySelector('.pet-editor')?.remove();const f=document.createElement('form');f.className='pet-editor';f.innerHTML=`<div class="pet-editor-title">${index==null?'Додати улюбленця':'Редагувати улюбленця'}</div><label>Ім’я<input name="pet_name" required maxlength="40" value="${esc(pet?.pet_name||'')}" placeholder="Наприклад, Боня"></label><label>Тип<select name="animal_type"><option value="dog">🐶 Собака</option><option value="cat">🐱 Кіт</option></select></label><label>Порода<input name="breed" maxlength="60" value="${esc(pet?.breed||'')}" placeholder="Порода"></label><label>Вік<input name="age" maxlength="30" value="${esc(pet?.age||'')}" placeholder="Наприклад, 3 роки"></label><div class="pet-editor-actions"><button type="button" class="ghost pet-editor-cancel">Скасувати</button><button type="submit" class="primary">Зберегти</button></div><p class="message pet-editor-message"></p>`;f.querySelector('[name="animal_type"]').value=pet?.animal_type||'dog';f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),v={pet_name:String(fd.get('pet_name')||'').trim(),animal_type:String(fd.get('animal_type')||'dog'),breed:String(fd.get('breed')||'').trim(),age:String(fd.get('age')||'').trim()},msg=f.querySelector('.pet-editor-message');if(v.pet_name.length<2){msg.textContent='❌ Вкажіть ім’я';return}const d=read(),pets=Array.isArray(d.pets)?d.pets:[];if(pets.some((p,i)=>i!==index&&String(p.pet_name||'').trim().toLowerCase()===v.pet_name.toLowerCase())){msg.textContent='❌ Такий улюбленець уже є';return}if(index==null)pets.push(v);else pets[index]=v;d.pets=pets;write(d);render();renderPicker(pets)};f.querySelector('.pet-editor-cancel').onclick=()=>f.remove();root.append(f);f.scrollIntoView({behavior:'smooth',block:'nearest'})}
let render=()=>{};
async function enhance(){const root=document.getElementById('profile-pets');let items=[];try{items=await window.customerAuth?.appointments?.()||[]}catch{}const pets=merge(items);renderPicker(pets);if(!root)return;render=()=>{const list=Array.isArray(read().pets)?read().pets:[];root.innerHTML=`<div class="profile-pets-head"><div><h3>Мої улюбленці</h3><p class="muted">Збережіть дані, щоб наступного разу записатися швидше.</p></div><button type="button" class="ghost pet-add-btn">+ Додати</button></div>`+(list.length?list.map((p,i)=>`<article class="pet-mini"><span class="pet-icon">${p.animal_type==='cat'?'🐱':'🐶'}</span><div class="pet-main"><b>${esc(p.pet_name)}</b><span>${esc(p.breed||'Порода не вказана')} · ${esc(p.age||'Вік не вказаний')}</span></div><div class="pet-manage-actions"><button type="button" class="ghost pet-edit-btn" data-index="${i}">Редагувати</button><button type="button" class="pet-book-btn" data-index="${i}">Записати знову</button><button type="button" class="pet-delete-btn" data-index="${i}">Видалити</button></div></article>`).join(''):`<div class="empty-state pet-empty"><div class="empty-icon">🐾</div><h3>Улюбленців ще немає</h3><p>Додайте першого — і дані збережуться для наступних записів.</p></div>`;root.querySelector('.pet-add-btn')?.addEventListener('click',()=>editor(root,{},null,render));root.querySelectorAll('.pet-edit-btn').forEach(b=>b.addEventListener('click',()=>editor(root,list[+b.dataset.index],+b.dataset.index,render)));root.querySelectorAll('.pet-delete-btn').forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.index;if(!list[i]||!confirm(`Видалити «${list[i].pet_name}» зі збережених улюбленців?`))return;const d=read();d.pets=(d.pets||[]).filter((_,n)=>n!==i);write(d);render();renderPicker(d.pets)}));root.querySelectorAll('.pet-book-btn').forEach(b=>b.addEventListener('click',()=>{const p=list[+b.dataset.index];if(p)book(p)}))};render()}
const wrap=window.renderCustomerProfile;if(typeof wrap==='function')window.renderCustomerProfile=async()=>{await wrap();await enhance()};window.addEventListener('hashchange',()=>{if(location.hash.slice(1)==='profile'||location.hash.slice(1)==='booking')setTimeout(enhance,80)});setTimeout(enhance,180);
})();
